package telegramcontrollers

import (
	"fmt"
	"service-platform/internal/pkg/fun"
)

// getLocalizedMessage returns the localized message based on language
func (h *TelegramHelper) getLocalizedMessage(lang, key string, args ...interface{}) string {
	messages := map[string]map[string]string{
		fun.LangID: {
			"welcome":                                 "Selamat datang di Bot Telegram! Pilih opsi:",
			"welcome_new_user":                        "👋 *Selamat datang!* \n\nSaya adalah asisten bot yang siap membantu Anda. Klik tombol di bawah untuk memulai:",
			"help":                                    "Perintah dan opsi yang tersedia:",
			"start":                                   "Mulai",
			"info":                                    "Info",
			"commands":                                "Daftar Perintah",
			"language":                                "Bahasa",
			"bot_info":                                "🤖 *Informasi Bot*\n\nIni adalah bot Telegram yang dibuat dengan Go.\n\nFitur:\n• Menu interaktif\n• Penanganan perintah\n• Query callback\n\nGunakan /help untuk opsi lebih lanjut.",
			"commands_list":                           "📋 *Perintah yang Tersedia*\n\n/start - Mulai bot dan tampilkan menu utama\n/help - Tampilkan bantuan dan opsi yang tersedia\n\n*Catatan:* Anda juga dapat mengklik tombol di atas untuk navigasi!",
			"unknown_command":                         "Perintah tidak dikenal. Gunakan /help untuk perintah yang tersedia.",
			"unknown_button":                          "Tombol tidak dikenal ditekan.",
			"button1":                                 "Anda menekan Tombol 1!",
			"button2":                                 "Anda menekan Tombol 2!",
			"select_language":                         "Pilih Bahasa / Select Language:",
			"language_set":                            "Bahasa berhasil diubah ke Bahasa Indonesia 🇮🇩",
			"message_received":                        "Pesan diterima: %s",
			"user_registration_failed":                "Gagal mendaftarkan pengguna. Silakan coba lagi.",
			"user_created_unverified":                 "Selamat datang! Akun Anda telah dibuat tetapi perlu verifikasi. Silakan hubungi Technical Support di %s untuk diverifikasi.",
			"database_error":                          "Kesalahan database. Silakan coba lagi.",
			"user_banned":                             "Akun Anda telah diblokir. Silakan hubungi administrator.",
			"user_unverified":                         "Akun Anda belum diverifikasi. Silakan hubungi Technical Support di %s untuk diverifikasi.",
			"quota_exceeded":                          "Kuota harian terlampaui (%d/%d). Silakan coba lagi besok.",
			"language_error":                          "Error mengatur bahasa.",
			"reaction_added":                          "Reaksi %s ditambahkan!",
			"hours":                                   "jam",
			"minutes":                                 "menit",
			"seconds":                                 "detik",
			"time_remaining":                          "Waktu tersisa sampai reset: %s",
			"share_phone":                             "📱 Bagikan Nomor Telepon",
			"cancel":                                  "❌ Batal",
			"registration_fullname_prompt":            "Masukkan nama lengkap Anda:",
			"registration_fullname_required":          "Nama lengkap wajib diisi. Silakan masukkan nama lengkap Anda:",
			"registration_username_prompt":            "Masukkan username Anda:",
			"registration_username_required":          "Username wajib diisi. Silakan masukkan username Anda:",
			"registration_email_prompt":               "Masukkan alamat email Anda:",
			"registration_invalid_email":              "Format email tidak valid. Silakan masukkan email yang benar:",
			"registration_invalid_email_detailed":     "Email %s tidak valid. Silakan masukkan alamat email yang benar:",
			"registration_invalid_usertype":           "Jenis pengguna tidak valid. Silakan pilih dari opsi yang tersedia.",
			"registration_phone_prompt":               "Masukkan nomor telepon Anda:",
			"registration_phone_required":             "Nomor telepon wajib diisi. Silakan masukkan nomor telepon Anda:",
			"registration_invalid_phone":              "Nomor telepon tidak valid. Silakan masukkan nomor telepon yang benar:",
			"registration_invalid_phone_detailed":     "Nomor telepon %s tidak valid untuk kode negara '%s'. Silakan masukkan nomor telepon yang benar:",
			"registration_usertype_prompt":            "Pilih jenis pengguna Anda:",
			"registration_select_usertype":            "Silakan pilih jenis pengguna dari opsi di bawah:",
			"registration_complete":                   "Pendaftaran selesai! Selamat datang di bot kami.",
			"registration_superuser_not_allowed":      "Anda tidak dapat mendaftar sebagai Super User. Nomor telepon tidak ditemukan dalam database Super User.",
			"registration_superuser_update_failed":    "Gagal memperbarui data Super User: %s. Silakan coba lagi.",
			"registration_tams_not_allowed":           "Anda tidak dapat mendaftar sebagai TA MS. Nomor telepon tidak ditemukan dalam database TA MS.",
			"registration_tams_update_failed":         "Gagal memperbarui data TA MS: %s. Silakan coba lagi.",
			"registration_headms_not_allowed":         "Anda tidak dapat mendaftar sebagai Head MS. Nomor telepon tidak ditemukan dalam database Head MS.",
			"registration_headms_update_failed":       "Gagal memperbarui data Head MS: %s. Silakan coba lagi.",
			"registration_technicianms_not_allowed":   "Anda tidak dapat mendaftar sebagai Teknisi MS. Nomor telepon %s tidak ditemukan dalam ODOOMS.",
			"registration_technicianms_update_failed": "Gagal memperbarui data Teknisi MS: %s. Silakan coba lagi.",
			"registration_chat_id_in_use":             "Chat ID sudah digunakan oleh pengguna lain yang sudah terverifikasi.",
			"usertype_common":                         "Pengguna Biasa",
			"usertype_super_user":                     "Super User",
			"usertype_technician_ms":                  "Teknisi Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Kepala Manage Service",
			"error":                                   "Terjadi kesalahan. Silakan coba lagi.",
			"registration_success_title":              "✅ Pendaftaran Berhasil!",
			"registration_details_fullname":           "👤 Nama Lengkap:",
			"registration_details_username":           "👨‍💻 Username:",
			"registration_details_email":              "📧 Email:",
			"registration_details_phone":              "📱 Telepon:",
			"registration_details_usertype":           "🏷️ Tipe Pengguna:",
			"registration_welcome_message":            "Selamat datang di bot kami! Anda sekarang dapat menggunakan semua fitur.",
		},
		fun.LangEN: {
			"welcome":                                 "Welcome to the Telegram Bot! Choose an option:",
			"welcome_new_user":                        "👋 *Welcome!* \n\nI'm your assistant bot ready to help. Click the button below to get started:",
			"help":                                    "Available commands and options:",
			"start":                                   "Start",
			"info":                                    "Info",
			"commands":                                "Commands List",
			"language":                                "Language",
			"bot_info":                                "🤖 *Bot Information*\n\nThis is a Telegram bot built with Go.\n\nFeatures:\n• Interactive menus\n• Command handling\n• Callback queries\n\nUse /help for more options.",
			"commands_list":                           "📋 *Available Commands*\n\n/start - Start the bot and show main menu\n/help - Show help and available options\n\n*Note:* You can also click the buttons above to navigate!",
			"unknown_command":                         "Unknown command. Use /help for available commands.",
			"unknown_button":                          "Unknown button pressed.",
			"button1":                                 "You pressed Button 1!",
			"button2":                                 "You pressed Button 2!",
			"select_language":                         "Pilih Bahasa / Select Language:",
			"language_set":                            "Language successfully changed to English 🇺🇸",
			"message_received":                        "Message received: %s",
			"user_registration_failed":                "Failed to register user. Please try again.",
			"user_created_unverified":                 "Welcome! Your account has been created but needs verification. Please contact Technical Support at %s to get verified.",
			"database_error":                          "Database error. Please try again.",
			"user_banned":                             "Your account has been banned. Please contact administrator.",
			"user_unverified":                         "Your account is not verified. Please contact Technical Support at %s to get verified.",
			"quota_exceeded":                          "Daily quota exceeded (%d/%d). Please try again tomorrow.",
			"language_error":                          "Error setting language.",
			"reaction_added":                          "Reaction %s added!",
			"hours":                                   "hours",
			"minutes":                                 "minutes",
			"seconds":                                 "seconds",
			"time_remaining":                          "Time remaining until reset: %s",
			"share_phone":                             "📱 Share Phone Number",
			"cancel":                                  "❌ Cancel",
			"registration_fullname_prompt":            "Enter your full name:",
			"registration_fullname_required":          "Full name is required. Please enter your full name:",
			"registration_username_prompt":            "Enter your username:",
			"registration_username_required":          "Username is required. Please enter your username:",
			"registration_email_prompt":               "Enter your email address:",
			"registration_invalid_email":              "Invalid email format. Please enter a valid email:",
			"registration_invalid_email_detailed":     "Email %s is not valid. Please enter a valid email address:",
			"registration_invalid_usertype":           "Invalid user type. Please select from the available options.",
			"registration_phone_prompt":               "Enter your phone number:",
			"registration_phone_required":             "Phone number is required. Please enter your phone number:",
			"registration_invalid_phone":              "Invalid phone number. Please enter a valid phone number:",
			"registration_invalid_phone_detailed":     "Phone number %s is not valid for country code '%s'. Please enter a valid phone number:",
			"registration_usertype_prompt":            "Select your user type:",
			"registration_select_usertype":            "Please select your user type from the options below:",
			"registration_complete":                   "Registration complete! Welcome to our bot.",
			"registration_superuser_not_allowed":      "You cannot register as Super User. Phone number not found in Super User database.",
			"registration_superuser_update_failed":    "Failed to update Super User data: %s. Please try again.",
			"registration_tams_not_allowed":           "You cannot register as TA MS. Phone number not found in TA MS database.",
			"registration_tams_update_failed":         "Failed to update TA MS data: %s. Please try again.",
			"registration_headms_not_allowed":         "You cannot register as Head MS. Phone number not found in Head MS database.",
			"registration_headms_update_failed":       "Failed to update Head MS data: %s. Please try again.",
			"registration_technicianms_not_allowed":   "You cannot register as Technician MS. Phone number %s not found in ODOOMS.",
			"registration_technicianms_update_failed": "Failed to update Technician MS data: %s. Please try again.",
			"registration_chat_id_in_use":             "Chat ID is already in use by another verified user.",
			"usertype_common":                         "Common User",
			"usertype_super_user":                     "Super User",
			"usertype_technician_ms":                  "Manage Service Technician",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Head of Manage Service",
			"error":                                   "An error occurred. Please try again.",
			"registration_success_title":              "✅ Registration Successful!",
			"registration_details_fullname":           "👤 Full Name:",
			"registration_details_username":           "👨‍💻 Username:",
			"registration_details_email":              "📧 Email:",
			"registration_details_phone":              "📱 Phone:",
			"registration_details_usertype":           "🏷️ User Type:",
			"registration_welcome_message":            "Welcome to our bot! You can now use all features.",
		},
		fun.LangES: {
			"welcome":                                 "¡Bienvenido al Bot de Telegram! Elige una opción:",
			"welcome_new_user":                        "👋 *¡Bienvenido!* \n\nSoy tu bot asistente listo para ayudarte. Haz clic en el botón de abajo para comenzar:",
			"help":                                    "Comandos y opciones disponibles:",
			"start":                                   "Inicio",
			"info":                                    "Info",
			"commands":                                "Lista de Comandos",
			"language":                                "Idioma",
			"bot_info":                                "🤖 *Información del Bot*\n\nEste es un bot de Telegram creado con Go.\n\nCaracterísticas:\n• Menús interactivos\n• Manejo de comandos\n• Consultas de callback\n\nUsa /help para más opciones.",
			"commands_list":                           "📋 *Comandos Disponibles*\n\n/start - Iniciar el bot y mostrar el menú principal\n/help - Mostrar ayuda y opciones disponibles\n\n*Nota:* ¡También puedes hacer clic en los botones de arriba para navegar!",
			"unknown_command":                         "Comando desconocido. Usa /help para comandos disponibles.",
			"unknown_button":                          "Botón desconocido presionado.",
			"button1":                                 "¡Presionaste el Botón 1!",
			"button2":                                 "¡Presionaste el Botón 2!",
			"select_language":                         "Selecciona Idioma / Select Language:",
			"language_set":                            "Idioma cambiado exitosamente a Español 🇪🇸",
			"message_received":                        "Mensaje recibido: %s",
			"user_registration_failed":                "Error al registrar usuario. Por favor, inténtalo de nuevo.",
			"user_created_unverified":                 "¡Bienvenido! Tu cuenta ha sido creada pero necesita verificación. Por favor, contacta al Soporte Técnico al %s para ser verificado.",
			"database_error":                          "Error de base de datos. Por favor, inténtalo de nuevo.",
			"user_banned":                             "Tu cuenta ha sido baneada. Por favor, contacta al administrador.",
			"user_unverified":                         "Tu cuenta no está verificada. Por favor, contacta al Soporte Técnico al %s para ser verificado.",
			"quota_exceeded":                          "Cuota diaria excedida (%d/%d). Por favor, inténtalo de nuevo mañana.",
			"language_error":                          "Error al configurar el idioma.",
			"reaction_added":                          "¡Reacción %s añadida!",
			"hours":                                   "horas",
			"minutes":                                 "minutos",
			"seconds":                                 "segundos",
			"time_remaining":                          "Tiempo restante hasta el reinicio: %s",
			"share_phone":                             "📱 Compartir Número de Teléfono",
			"cancel":                                  "❌ Cancelar",
			"registration_fullname_prompt":            "Ingresa tu nombre completo:",
			"registration_fullname_required":          "El nombre completo es obligatorio. Por favor ingresa tu nombre completo:",
			"registration_username_prompt":            "Ingresa tu nombre de usuario:",
			"registration_username_required":          "El nombre de usuario es obligatorio. Por favor ingresa tu nombre de usuario:",
			"registration_email_prompt":               "Ingresa tu dirección de correo electrónico:",
			"registration_invalid_email":              "Formato de correo electrónico inválido. Por favor ingresa un correo válido:",
			"registration_invalid_email_detailed":     "El correo electrónico %s no es válido. Por favor ingresa una dirección de correo válida:",
			"registration_invalid_usertype":           "Tipo de usuario inválido. Por favor selecciona de las opciones disponibles.",
			"registration_phone_prompt":               "Ingresa tu número de teléfono:",
			"registration_phone_required":             "El número de teléfono es obligatorio. Por favor ingresa tu número de teléfono:",
			"registration_invalid_phone":              "Número de teléfono inválido. Por favor ingresa un número válido:",
			"registration_invalid_phone_detailed":     "El número de teléfono %s no es válido para el código de país '%s'. Por favor ingresa un número válido:",
			"registration_usertype_prompt":            "Selecciona tu tipo de usuario:",
			"registration_select_usertype":            "Por favor selecciona tu tipo de usuario de las opciones a continuación:",
			"registration_complete":                   "¡Registro completado! ¡Bienvenido a nuestro bot!",
			"registration_superuser_not_allowed":      "No puede registrarse como Super Usuario. Número de teléfono no encontrado en la base de datos de Super Usuario.",
			"registration_superuser_update_failed":    "Error al actualizar los datos del Super Usuario: %s. Por favor, inténtelo de nuevo.",
			"registration_tams_not_allowed":           "No puede registrarse como TA MS. Número de teléfono no encontrado en la base de datos de TA MS.",
			"registration_tams_update_failed":         "Error al actualizar los datos del TA MS: %s. Por favor, inténtelo de nuevo.",
			"registration_headms_not_allowed":         "No puede registrarse como Head MS. Número de teléfono no encontrado en la base de datos de Head MS.",
			"registration_headms_update_failed":       "Error al actualizar los datos del Head MS: %s. Por favor, inténtelo de nuevo.",
			"registration_technicianms_not_allowed":   "No puede registrarse como Técnico MS. Número de teléfono %s no encontrado en ODOOMS.",
			"registration_technicianms_update_failed": "Error al actualizar los datos del Técnico MS: %s. Por favor, inténtelo de nuevo.",
			"registration_chat_id_in_use":             "El ID de chat ya está en uso por otro usuario verificado.",
			"usertype_common":                         "Usuario Común",
			"usertype_super_user":                     "Super Usuario",
			"usertype_technician_ms":                  "Técnico de Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Jefe de Manage Service",
			"error":                                   "Ocurrió un error. Por favor inténtalo de nuevo.",
			"registration_success_title":              "✅ ¡Registro Exitoso!",
			"registration_details_fullname":           "👤 Nombre Completo:",
			"registration_details_username":           "👨‍💻 Nombre de Usuario:",
			"registration_details_email":              "📧 Correo Electrónico:",
			"registration_details_phone":              "📱 Teléfono:",
			"registration_details_usertype":           "🏷️ Tipo de Usuario:",
			"registration_welcome_message":            "¡Bienvenido a nuestro bot! Ahora puedes usar todas las funciones.",
		},
		fun.LangFR: {
			"welcome":                                 "Bienvenue sur le Bot Telegram ! Choisissez une option :",
			"welcome_new_user":                        "👋 *Bienvenue !* \n\nJe suis votre bot assistant prêt à vous aider. Cliquez sur le bouton ci-dessous pour commencer :",
			"help":                                    "Commandes et options disponibles :",
			"start":                                   "Démarrer",
			"info":                                    "Info",
			"commands":                                "Liste des Commandes",
			"language":                                "Langue",
			"bot_info":                                "🤖 *Informations sur le Bot*\n\nCeci est un bot Telegram créé avec Go.\n\nFonctionnalités :\n• Menus interactifs\n• Gestion des commandes\n• Requêtes de callback\n\nUtilisez /help pour plus d'options.",
			"commands_list":                           "📋 *Commandes Disponibles*\n\n/start - Démarrer le bot et afficher le menu principal\n/help - Afficher l'aide et les options disponibles\n\n*Note :* Vous pouvez également cliquer sur les boutons ci-dessus pour naviguer !",
			"unknown_command":                         "Commande inconnue. Utilisez /help pour les commandes disponibles.",
			"unknown_button":                          "Bouton inconnu pressé.",
			"button1":                                 "Vous avez appuyé sur le Bouton 1 !",
			"button2":                                 "Vous avez appuyé sur le Bouton 2 !",
			"select_language":                         "Sélectionner la Langue / Select Language :",
			"language_set":                            "Langue changée avec succès en Français 🇫🇷",
			"message_received":                        "Message reçu : %s",
			"user_registration_failed":                "Échec de l'enregistrement de l'utilisateur. Veuillez réessayer.",
			"user_created_unverified":                 "Bienvenue ! Votre compte a été créé mais nécessite une vérification. Veuillez contacter le Support Technique au %s pour être vérifié.",
			"database_error":                          "Erreur de base de données. Veuillez réessayer.",
			"user_banned":                             "Votre compte a été banni. Veuillez contacter l'administrateur.",
			"user_unverified":                         "Votre compte n'est pas vérifié. Veuillez contacter le Support Technique au %s pour être vérifié.",
			"quota_exceeded":                          "Quota quotidien dépassé (%d/%d). Veuillez réessayer demain.",
			"language_error":                          "Erreur lors de la configuration de la langue.",
			"reaction_added":                          "Réaction %s ajoutée !",
			"hours":                                   "heures",
			"minutes":                                 "minutes",
			"seconds":                                 "secondes",
			"time_remaining":                          "Temps restant jusqu'à la réinitialisation: %s",
			"share_phone":                             "📱 Partager le Numéro de Téléphone",
			"cancel":                                  "❌ Annuler",
			"registration_fullname_prompt":            "Entrez votre nom complet :",
			"registration_fullname_required":          "Le nom complet est requis. Veuillez entrer votre nom complet :",
			"registration_username_prompt":            "Entrez votre nom d'utilisateur :",
			"registration_username_required":          "Le nom d'utilisateur est requis. Veuillez entrer votre nom d'utilisateur :",
			"registration_email_prompt":               "Entrez votre adresse e-mail :",
			"registration_invalid_email":              "Format d'e-mail invalide. Veuillez entrer un e-mail valide :",
			"registration_invalid_email_detailed":     "L'e-mail %s n'est pas valide. Veuillez entrer une adresse e-mail valide :",
			"registration_invalid_usertype":           "Type d'utilisateur invalide. Veuillez sélectionner parmi les options disponibles.",
			"registration_phone_prompt":               "Entrez votre numéro de téléphone :",
			"registration_phone_required":             "Le numéro de téléphone est requis. Veuillez entrer votre numéro de téléphone :",
			"registration_invalid_phone":              "Numéro de téléphone invalide. Veuillez entrer un numéro de téléphone valide :",
			"registration_invalid_phone_detailed":     "Le numéro de téléphone %s n'est pas valide pour le code pays '%s'. Veuillez entrer un numéro valide :",
			"registration_usertype_prompt":            "Sélectionnez votre type d'utilisateur :",
			"registration_select_usertype":            "Veuillez sélectionner votre type d'utilisateur parmi les options ci-dessous :",
			"registration_complete":                   "Inscription terminée ! Bienvenue sur notre bot.",
			"registration_superuser_not_allowed":      "Vous ne pouvez pas vous inscrire en tant que Super Utilisateur. Numéro de téléphone introuvable dans la base de données Super Utilisateur.",
			"registration_superuser_update_failed":    "Échec de la mise à jour des données du Super Utilisateur: %s. Veuillez réessayer.",
			"registration_tams_not_allowed":           "Vous ne pouvez pas vous inscrire en tant que TA MS. Numéro de téléphone introuvable dans la base de données TA MS.",
			"registration_tams_update_failed":         "Échec de la mise à jour des données du TA MS: %s. Veuillez réessayer.",
			"registration_headms_not_allowed":         "Vous ne pouvez pas vous inscrire en tant que Head MS. Numéro de téléphone introuvable dans la base de données Head MS.",
			"registration_headms_update_failed":       "Échec de la mise à jour des données du Head MS: %s. Veuillez réessayer.",
			"registration_technicianms_not_allowed":   "Vous ne pouvez pas vous inscrire en tant que Technicien MS. Numéro de téléphone %s introuvable dans ODOOMS.",
			"registration_technicianms_update_failed": "Échec de la mise à jour des données du Technicien MS: %s. Veuillez réessayer.",
			"registration_chat_id_in_use":             "L'ID de chat est déjà utilisé par un autre utilisateur vérifié.",
			"usertype_common":                         "Utilisateur Commun",
			"usertype_super_user":                     "Super Utilisateur",
			"usertype_technician_ms":                  "Technicien Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Chef de Manage Service",
			"error":                                   "Une erreur s'est produite. Veuillez réessayer.",
			"registration_success_title":              "✅ Inscription Réussie !",
			"registration_details_fullname":           "👤 Nom Complet :",
			"registration_details_username":           "👨‍💻 Nom d'Utilisateur :",
			"registration_details_email":              "📧 E-mail :",
			"registration_details_phone":              "📱 Téléphone :",
			"registration_details_usertype":           "🏷️ Type d'Utilisateur :",
			"registration_welcome_message":            "Bienvenue sur notre bot ! Vous pouvez maintenant utiliser toutes les fonctionnalités.",
		},
		fun.LangDE: {
			"welcome":                                 "Willkommen beim Telegram Bot! Wählen Sie eine Option:",
			"welcome_new_user":                        "👋 *Willkommen!* \n\nIch bin Ihr Assistenten-Bot und bereit, Ihnen zu helfen. Klicken Sie auf die Schaltfläche unten, um zu beginnen:",
			"help":                                    "Verfügbare Befehle und Optionen:",
			"start":                                   "Start",
			"info":                                    "Info",
			"commands":                                "Befehlsliste",
			"language":                                "Sprache",
			"bot_info":                                "🤖 *Bot-Informationen*\n\nDies ist ein Telegram-Bot, der mit Go erstellt wurde.\n\nFunktionen:\n• Interaktive Menüs\n• Befehlsverarbeitung\n• Callback-Abfragen\n\nVerwenden Sie /help für weitere Optionen.",
			"commands_list":                           "📋 *Verfügbare Befehle*\n\n/start - Bot starten und Hauptmenü anzeigen\n/help - Hilfe und verfügbare Optionen anzeigen\n\n*Hinweis:* Sie können auch auf die Schaltflächen oben klicken, um zu navigieren!",
			"unknown_command":                         "Unbekannter Befehl. Verwenden Sie /help für verfügbare Befehle.",
			"unknown_button":                          "Unbekannte Schaltfläche gedrückt.",
			"button1":                                 "Sie haben Schaltfläche 1 gedrückt!",
			"button2":                                 "Sie haben Schaltfläche 2 gedrückt!",
			"select_language":                         "Sprache auswählen / Select Language:",
			"language_set":                            "Sprache erfolgreich zu Deutsch 🇩🇪 geändert",
			"message_received":                        "Nachricht erhalten: %s",
			"user_registration_failed":                "Benutzerregistrierung fehlgeschlagen. Bitte versuchen Sie es erneut.",
			"user_created_unverified":                 "Willkommen! Ihr Konto wurde erstellt, erfordert aber eine Überprüfung. Bitte kontaktieren Sie den technischen Support unter %s zur Überprüfung.",
			"database_error":                          "Datenbankfehler. Bitte versuchen Sie es erneut.",
			"user_banned":                             "Ihr Konto wurde gesperrt. Bitte kontaktieren Sie den Administrator.",
			"user_unverified":                         "Ihr Konto ist nicht verifiziert. Bitte kontaktieren Sie den technischen Support unter %s zur Überprüfung.",
			"quota_exceeded":                          "Tägliches Kontingent überschritten (%d/%d). Bitte versuchen Sie es morgen erneut.",
			"language_error":                          "Fehler beim Festlegen der Sprache.",
			"reaction_added":                          "Reaktion %s hinzugefügt!",
			"hours":                                   "Stunden",
			"minutes":                                 "Minuten",
			"seconds":                                 "Sekunden",
			"time_remaining":                          "Verbleibende Zeit bis zum Zurücksetzen: %s",
			"share_phone":                             "📱 Telefonnummer Teilen",
			"cancel":                                  "❌ Abbrechen",
			"registration_fullname_prompt":            "Geben Sie Ihren vollständigen Namen ein:",
			"registration_fullname_required":          "Vollständiger Name ist erforderlich. Bitte geben Sie Ihren vollständigen Namen ein:",
			"registration_username_prompt":            "Geben Sie Ihren Benutzernamen ein:",
			"registration_username_required":          "Benutzername ist erforderlich. Bitte geben Sie Ihren Benutzernamen ein:",
			"registration_email_prompt":               "Geben Sie Ihre E-Mail-Adresse ein:",
			"registration_invalid_email":              "Ungültiges E-Mail-Format. Bitte geben Sie eine gültige E-Mail ein:",
			"registration_invalid_email_detailed":     "Die E-Mail %s ist nicht gültig. Bitte geben Sie eine gültige E-Mail-Adresse ein:",
			"registration_invalid_usertype":           "Ungültiger Benutzertyp. Bitte wählen Sie aus den verfügbaren Optionen.",
			"registration_phone_prompt":               "Geben Sie Ihre Telefonnummer ein:",
			"registration_phone_required":             "Telefonnummer ist erforderlich. Bitte geben Sie Ihre Telefonnummer ein:",
			"registration_invalid_phone":              "Ungültige Telefonnummer. Bitte geben Sie eine gültige Telefonnummer ein:",
			"registration_invalid_phone_detailed":     "Die Telefonnummer %s ist für den Ländercode '%s' nicht gültig. Bitte geben Sie eine gültige Telefonnummer ein:",
			"registration_usertype_prompt":            "Wählen Sie Ihren Benutzertyp:",
			"registration_select_usertype":            "Bitte wählen Sie Ihren Benutzertyp aus den folgenden Optionen:",
			"registration_complete":                   "Registrierung abgeschlossen! Willkommen bei unserem Bot.",
			"registration_superuser_not_allowed":      "Sie können sich nicht als Super User registrieren. Telefonnummer nicht in der Super User Datenbank gefunden.",
			"registration_superuser_update_failed":    "Fehler beim Aktualisieren der Super-Benutzerdaten: %s. Bitte versuchen Sie es erneut.",
			"registration_tams_not_allowed":           "Sie können sich nicht als TA MS registrieren. Telefonnummer nicht in der TA MS Datenbank gefunden.",
			"registration_tams_update_failed":         "Fehler beim Aktualisieren der TA MS-Benutzerdaten: %s. Bitte versuchen Sie es erneut.",
			"registration_headms_not_allowed":         "Sie können sich nicht als Head MS registrieren. Telefonnummer nicht in der Head MS Datenbank gefunden.",
			"registration_headms_update_failed":       "Fehler beim Aktualisieren der Head MS-Benutzerdaten: %s. Bitte versuchen Sie es erneut.",
			"registration_technicianms_not_allowed":   "Sie können sich nicht als Techniker MS registrieren. Telefonnummer %s nicht in ODOOMS gefunden.",
			"registration_technicianms_update_failed": "Fehler beim Aktualisieren der Techniker MS-Benutzerdaten: %s. Bitte versuchen Sie es erneut.",
			"registration_chat_id_in_use":             "Chat-ID wird bereits von einem anderen verifizierten Benutzer verwendet.",
			"usertype_common":                         "Gemeinsamer Benutzer",
			"usertype_super_user":                     "Super-Benutzer",
			"usertype_technician_ms":                  "Manage Service Techniker",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Leiter Manage Service",
			"error":                                   "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
			"registration_success_title":              "✅ Registrierung Erfolgreich!",
			"registration_details_fullname":           "👤 Vollständiger Name:",
			"registration_details_username":           "👨‍💻 Benutzername:",
			"registration_details_email":              "📧 E-Mail:",
			"registration_details_phone":              "📱 Telefon:",
			"registration_details_usertype":           "🏷️ Benutzertyp:",
			"registration_welcome_message":            "Willkommen bei unserem Bot! Sie können jetzt alle Funktionen nutzen.",
		},
		fun.LangPT: {
			"welcome":                                 "Bem-vindo ao Bot do Telegram! Escolha uma opção:",
			"welcome_new_user":                        "👋 *Bem-vindo!* \n\nSou seu bot assistente pronto para ajudar. Clique no botão abaixo para começar:",
			"help":                                    "Comandos e opções disponíveis:",
			"start":                                   "Iniciar",
			"info":                                    "Info",
			"commands":                                "Lista de Comandos",
			"language":                                "Idioma",
			"bot_info":                                "🤖 *Informações do Bot*\n\nEste é um bot do Telegram criado com Go.\n\nRecursos:\n• Menus interativos\n• Tratamento de comandos\n• Consultas de callback\n\nUse /help para mais opções.",
			"commands_list":                           "📋 *Comandos Disponíveis*\n\n/start - Iniciar o bot e mostrar o menu principal\n/help - Mostrar ajuda e opções disponíveis\n\n*Nota:* Você também pode clicar nos botões acima para navegar!",
			"unknown_command":                         "Comando desconhecido. Use /help para comandos disponíveis.",
			"unknown_button":                          "Botão desconhecido pressionado.",
			"button1":                                 "Você pressionou o Botão 1!",
			"button2":                                 "Você pressionou o Botão 2!",
			"select_language":                         "Selecionar Idioma / Select Language:",
			"language_set":                            "Idioma alterado com sucesso para Português 🇵🇹",
			"message_received":                        "Mensagem recebida: %s",
			"user_registration_failed":                "Falha no registro do usuário. Por favor, tente novamente.",
			"user_created_unverified":                 "Bem-vindo! Sua conta foi criada, mas requer verificação. Por favor, contate o suporte técnico em %s para verificação.",
			"database_error":                          "Erro de banco de dados. Por favor, tente novamente.",
			"user_banned":                             "Sua conta foi banida. Por favor, contate o administrador.",
			"user_unverified":                         "Sua conta não está verificada. Por favor, contate o suporte técnico em %s para verificação.",
			"quota_exceeded":                          "Cota diária excedida (%d/%d). Por favor, tente novamente amanhã.",
			"language_error":                          "Erro ao definir o idioma.",
			"reaction_added":                          "Reação %s adicionada!",
			"hours":                                   "horas",
			"minutes":                                 "minutos",
			"seconds":                                 "segundos",
			"time_remaining":                          "Tempo restante até a redefinição: %s",
			"share_phone":                             "📱 Compartilhar Número de Telefone",
			"cancel":                                  "❌ Cancelar",
			"registration_fullname_prompt":            "Digite seu nome completo:",
			"registration_fullname_required":          "Nome completo é obrigatório. Por favor, digite seu nome completo:",
			"registration_username_prompt":            "Digite seu nome de usuário:",
			"registration_username_required":          "Nome de usuário é obrigatório. Por favor, digite seu nome de usuário:",
			"registration_email_prompt":               "Digite seu endereço de e-mail:",
			"registration_invalid_email":              "Formato de e-mail inválido. Por favor, digite um e-mail válido:",
			"registration_invalid_email_detailed":     "O e-mail %s não é válido. Por favor, digite um endereço de e-mail válido:",
			"registration_invalid_usertype":           "Tipo de usuário inválido. Por favor, selecione das opções disponíveis.",
			"registration_phone_prompt":               "Digite seu número de telefone:",
			"registration_phone_required":             "Número de telefone é obrigatório. Por favor, digite seu número de telefone:",
			"registration_invalid_phone":              "Número de telefone inválido. Por favor, digite um número válido:",
			"registration_invalid_phone_detailed":     "O número de telefone %s não é válido para o código do país '%s'. Por favor, digite um número válido:",
			"registration_usertype_prompt":            "Selecione seu tipo de usuário:",
			"registration_select_usertype":            "Por favor, selecione seu tipo de usuário das opções abaixo:",
			"registration_complete":                   "Registro concluído! Bem-vindo ao nosso bot.",
			"registration_superuser_not_allowed":      "Você não pode se registrar como Super Usuário. Número de telefone não encontrado no banco de dados do Super Usuário.",
			"registration_superuser_update_failed":    "Falha ao atualizar os dados do Super Usuário: %s. Por favor, tente novamente.",
			"registration_tams_not_allowed":           "Você não pode se registrar como TA MS. Número de telefone não encontrado no banco de dados do TA MS.",
			"registration_tams_update_failed":         "Falha ao atualizar os dados do TA MS: %s. Por favor, tente novamente.",
			"registration_headms_not_allowed":         "Você não pode se registrar como Head MS. Número de telefone não encontrado no banco de dados do Head MS.",
			"registration_headms_update_failed":       "Falha ao atualizar os dados do Head MS: %s. Por favor, tente novamente.",
			"registration_technicianms_not_allowed":   "Você não pode se registrar como Técnico MS. Número de telefone %s não encontrado no ODOOMS.",
			"registration_technicianms_update_failed": "Falha ao atualizar os dados do Técnico MS: %s. Por favor, tente novamente.",
			"registration_chat_id_in_use":             "O ID do chat já está em uso por outro usuário verificado.",
			"usertype_common":                         "Usuário Comum",
			"usertype_super_user":                     "Super Usuário",
			"usertype_technician_ms":                  "Técnico de Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Chefe de Manage Service",
			"error":                                   "Ocorreu um erro. Por favor, tente novamente.",
			"registration_success_title":              "✅ Registro Bem-Sucedido!",
			"registration_details_fullname":           "👤 Nome Completo:",
			"registration_details_username":           "👨‍💻 Nome de Usuário:",
			"registration_details_email":              "📧 E-mail:",
			"registration_details_phone":              "📱 Telefone:",
			"registration_details_usertype":           "🏷️ Tipo de Usuário:",
			"registration_welcome_message":            "Bem-vindo ao nosso bot! Agora você pode usar todas as funções.",
		},
		fun.LangRU: {
			"welcome":                                 "Добро пожаловать в Telegram Bot! Выберите вариант:",
			"welcome_new_user":                        "👋 *Добро пожаловать!* \n\nЯ ваш помощник-бот, готовый помочь. Нажмите кнопку ниже, чтобы начать:",
			"help":                                    "Доступные команды и опции:",
			"start":                                   "Старт",
			"info":                                    "Инфо",
			"commands":                                "Список Команд",
			"language":                                "Язык",
			"bot_info":                                "🤖 *Информация о Боте*\n\nЭто бот Telegram, созданный с помощью Go.\n\nФункции:\n• Интерактивные меню\n• Обработка команд\n• Callback-запросы\n\nИспользуйте /help для дополнительных опций.",
			"commands_list":                           "📋 *Доступные Команды*\n\n/start - Запустить бота и показать главное меню\n/help - Показать справку и доступные опции\n\n*Примечание:* Вы также можете нажимать кнопки выше для навигации!",
			"unknown_command":                         "Неизвестная команда. Используйте /help для доступных команд.",
			"unknown_button":                          "Нажата неизвестная кнопка.",
			"button1":                                 "Вы нажали Кнопку 1!",
			"button2":                                 "Вы нажали Кнопку 2!",
			"select_language":                         "Выбрать Язык / Select Language:",
			"language_set":                            "Язык успешно изменен на Русский 🇷🇺",
			"message_received":                        "Сообщение получено: %s",
			"user_registration_failed":                "Не удалось зарегистрировать пользователя. Пожалуйста, попробуйте снова.",
			"user_created_unverified":                 "Добро пожаловать! Ваша учетная запись создана, но требует проверки. Пожалуйста, обратитесь в техническую поддержку по номеру %s для проверки.",
			"database_error":                          "Ошибка базы данных. Пожалуйста, попробуйте снова.",
			"user_banned":                             "Ваша учетная запись заблокирована. Пожалуйста, обратитесь к администратору.",
			"user_unverified":                         "Ваша учетная запись не проверена. Пожалуйста, обратитесь в техническую поддержку по номеру %s для проверки.",
			"quota_exceeded":                          "Дневная квота превышена (%d/%d). Пожалуйста, попробуйте завтра.",
			"language_error":                          "Ошибка при установке языка.",
			"reaction_added":                          "Реакция %s добавлена!",
			"hours":                                   "часов",
			"minutes":                                 "минут",
			"seconds":                                 "секунд",
			"time_remaining":                          "Время до сброса: %s",
			"share_phone":                             "📱 Поделиться Номером Телефона",
			"cancel":                                  "❌ Отмена",
			"registration_fullname_prompt":            "Введите ваше полное имя:",
			"registration_fullname_required":          "Полное имя обязательно. Пожалуйста, введите ваше полное имя:",
			"registration_username_prompt":            "Введите ваше имя пользователя:",
			"registration_username_required":          "Имя пользователя обязательно. Пожалуйста, введите ваше имя пользователя:",
			"registration_email_prompt":               "Введите ваш адрес электронной почты:",
			"registration_invalid_email":              "Неверный формат электронной почты. Пожалуйста, введите действительный адрес:",
			"registration_invalid_email_detailed":     "Электронная почта %s недействительна. Пожалуйста, введите действительный адрес электронной почты:",
			"registration_invalid_usertype":           "Недопустимый тип пользователя. Пожалуйста, выберите из доступных вариантов.",
			"registration_phone_prompt":               "Введите ваш номер телефона:",
			"registration_phone_required":             "Номер телефона обязателен. Пожалуйста, введите ваш номер телефона:",
			"registration_invalid_phone":              "Неверный номер телефона. Пожалуйста, введите действительный номер:",
			"registration_invalid_phone_detailed":     "Номер телефона %s недействителен для кода страны '%s'. Пожалуйста, введите действительный номер:",
			"registration_usertype_prompt":            "Выберите ваш тип пользователя:",
			"registration_select_usertype":            "Пожалуйста, выберите ваш тип пользователя из вариантов ниже:",
			"registration_complete":                   "Регистрация завершена! Добро пожаловать в наш бот.",
			"registration_superuser_not_allowed":      "Вы не можете зарегистрироваться как Супер Пользователь. Номер телефона не найден в базе данных Супер Пользователя.",
			"registration_superuser_update_failed":    "Не удалось обновить данные суперпользователя: %s. Пожалуйста, попробуйте еще раз.",
			"registration_tams_not_allowed":           "Вы не можете зарегистрироваться как TA MS. Номер телефона не найден в базе данных TA MS.",
			"registration_tams_update_failed":         "Не удалось обновить данные TA MS: %s. Пожалуйста, попробуйте еще раз.",
			"registration_headms_not_allowed":         "Вы не можете зарегистрироваться как Head MS. Номер телефона не найден в базе данных Head MS.",
			"registration_headms_update_failed":       "Не удалось обновить данные Head MS: %s. Пожалуйста, попробуйте еще раз.",
			"registration_technicianms_not_allowed":   "Вы не можете зарегистрироваться как Техник MS. Номер телефона %s не найден в ODOOMS.",
			"registration_technicianms_update_failed": "Не удалось обновить данные Техник MS: %s. Пожалуйста, попробуйте еще раз.",
			"registration_chat_id_in_use":             "ID чата уже используется другим проверенным пользователем.",
			"usertype_common":                         "Обычный Пользователь",
			"usertype_super_user":                     "Супер Пользователь",
			"usertype_technician_ms":                  "Техник Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Глава Manage Service",
			"error":                                   "Произошла ошибка. Пожалуйста, попробуйте снова.",
			"registration_success_title":              "✅ Регистрация Успешна!",
			"registration_details_fullname":           "👤 Полное Имя:",
			"registration_details_username":           "👨‍💻 Имя Пользователя:",
			"registration_details_email":              "📧 Электронная Почта:",
			"registration_details_phone":              "📱 Телефон:",
			"registration_details_usertype":           "🏷️ Тип Пользователя:",
			"registration_welcome_message":            "Добро пожаловать в наш бот! Теперь вы можете использовать все функции.",
		},
		fun.LangJP: {
			"welcome":                                 "Telegram Botへようこそ！オプションを選択してください：",
			"welcome_new_user":                        "👋 *ようこそ！* \n\n私はお手伝いできるアシスタントボットです。下のボタンをクリックして開始してください：",
			"help":                                    "利用可能なコマンドとオプション：",
			"start":                                   "スタート",
			"info":                                    "情報",
			"commands":                                "コマンドリスト",
			"language":                                "言語",
			"bot_info":                                "🤖 *Bot情報*\n\nこれはGoで作成されたTelegram Botです。\n\n機能：\n• インタラクティブメニュー\n• コマンド処理\n• コールバッククエリ\n\n詳細オプションについては/helpを使用してください。",
			"commands_list":                           "📋 *利用可能なコマンド*\n\n/start - Botを起動しメインメニューを表示\n/help - ヘルプと利用可能なオプションを表示\n\n*注意：* 上のボタンをクリックしてナビゲートすることもできます！",
			"unknown_command":                         "不明なコマンドです。利用可能なコマンドについては/helpを使用してください。",
			"unknown_button":                          "不明なボタンが押されました。",
			"button1":                                 "ボタン1を押しました！",
			"button2":                                 "ボタン2を押しました！",
			"select_language":                         "言語を選択 / Select Language:",
			"language_set":                            "言語が日本語 🇯🇵 に正常に変更されました",
			"message_received":                        "メッセージを受信しました：%s",
			"user_registration_failed":                "ユーザー登録に失敗しました。もう一度お試しください。",
			"user_created_unverified":                 "ようこそ！アカウントが作成されましたが、確認が必要です。確認のため、%s のテクニカルサポートにお問い合わせください。",
			"database_error":                          "データベースエラー。もう一度お試しください。",
			"user_banned":                             "アカウントが禁止されました。管理者にお問い合わせください。",
			"user_unverified":                         "アカウントが確認されていません。確認のため、%s のテクニカルサポートにお問い合わせください。",
			"quota_exceeded":                          "1日のクォータを超えました（%d/%d）。明日もう一度お試しください。",
			"language_error":                          "言語設定エラー。",
			"reaction_added":                          "リアクション %s が追加されました！",
			"hours":                                   "時間",
			"minutes":                                 "分",
			"seconds":                                 "秒",
			"time_remaining":                          "リセットまで残り時間: %s",
			"share_phone":                             "📱 電話番号を共有",
			"cancel":                                  "❌ キャンセル",
			"registration_fullname_prompt":            "フルネームを入力してください：",
			"registration_fullname_required":          "フルネームは必須です。フルネームを入力してください：",
			"registration_username_prompt":            "ユーザー名を入力してください：",
			"registration_username_required":          "ユーザー名は必須です。ユーザー名を入力してください：",
			"registration_email_prompt":               "メールアドレスを入力してください：",
			"registration_invalid_email":              "メールアドレスの形式が無効です。有効なメールアドレスを入力してください：",
			"registration_invalid_email_detailed":     "メールアドレス %s は無効です。有効なメールアドレスを入力してください：",
			"registration_invalid_usertype":           "無効なユーザータイプです。利用可能なオプションから選択してください。",
			"registration_phone_prompt":               "電話番号を入力してください：",
			"registration_phone_required":             "電話番号は必須です。電話番号を入力してください：",
			"registration_invalid_phone":              "無効な電話番号です。有効な電話番号を入力してください：",
			"registration_invalid_phone_detailed":     "電話番号 %s は国コード '%s' に対して無効です。有効な電話番号を入力してください：",
			"registration_usertype_prompt":            "ユーザータイプを選択してください：",
			"registration_select_usertype":            "以下のオプションからユーザータイプを選択してください：",
			"registration_complete":                   "登録完了！当社のボットへようこそ。",
			"registration_superuser_not_allowed":      "スーパーユーザーとして登録できません。スーパーユーザーデータベースに電話番号が見つかりません。",
			"registration_superuser_update_failed":    "スーパーユーザーのデータ更新に失敗しました: %s. もう一度お試しください。",
			"registration_tams_not_allowed":           "TA MSとして登録できません。TA MSデータベースに電話番号が見つかりません。",
			"registration_tams_update_failed":         "TA MSのデータ更新に失敗しました: %s. もう一度お試しください。",
			"registration_headms_not_allowed":         "Head MSとして登録できません。Head MSデータベースに電話番号が見つかりません。",
			"registration_headms_update_failed":       "Head MSのデータ更新に失敗しました: %s. もう一度お試しください。",
			"registration_technicianms_not_allowed":   "Technician MSとして登録できません。電話番号 %s がODOOMSに見つかりません。",
			"registration_technicianms_update_failed": "Technician MSのデータ更新に失敗しました: %s. もう一度お試しください。",
			"registration_chat_id_in_use":             "チャットIDは既に別の検証済みユーザーによって使用されています。",
			"usertype_common":                         "一般ユーザー",
			"usertype_super_user":                     "スーパーユーザー",
			"usertype_technician_ms":                  "Manage Service技術者",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Manage Service責任者",
			"error":                                   "エラーが発生しました。もう一度お試しください。",
			"registration_success_title":              "✅ 登録成功！",
			"registration_details_fullname":           "👤 フルネーム:",
			"registration_details_username":           "👨‍💻 ユーザー名:",
			"registration_details_email":              "📧 メール:",
			"registration_details_phone":              "📱 電話:",
			"registration_details_usertype":           "🏷️ ユーザータイプ:",
			"registration_welcome_message":            "当社のボットへようこそ！すべての機能を使用できるようになりました。",
		},
		fun.LangCN: {
			"welcome":                                 "欢迎使用 Telegram Bot！选择一个选项：",
			"welcome_new_user":                        "👋 *欢迎！* \n\n我是您的助手机器人，随时准备帮助您。点击下面的按钮开始：",
			"help":                                    "可用的命令和选项：",
			"start":                                   "开始",
			"info":                                    "信息",
			"commands":                                "命令列表",
			"language":                                "语言",
			"bot_info":                                "🤖 *Bot信息*\n\n这是一个使用Go创建的Telegram Bot。\n\n功能：\n• 交互式菜单\n• 命令处理\n• 回调查询\n\n使用/help获取更多选项。",
			"commands_list":                           "📋 *可用命令*\n\n/start - 启动Bot并显示主菜单\n/help - 显示帮助和可用选项\n\n*注意：* 您也可以点击上面的按钮进行导航！",
			"unknown_command":                         "未知命令。使用/help查看可用命令。",
			"unknown_button":                          "按下了未知按钮。",
			"button1":                                 "您按下了按钮1！",
			"button2":                                 "您按下了按钮2！",
			"select_language":                         "选择语言 / Select Language:",
			"language_set":                            "语言已成功更改为中文 🇨🇳",
			"message_received":                        "收到消息：%s",
			"user_registration_failed":                "用户注册失败。请重试。",
			"user_created_unverified":                 "欢迎！您的账户已创建，但需要验证。请联系 %s 的技术支持进行验证。",
			"database_error":                          "数据库错误。请重试。",
			"user_banned":                             "您的账户已被禁止。请联系管理员。",
			"user_unverified":                         "您的账户未经验证。请联系 %s 的技术支持进行验证。",
			"quota_exceeded":                          "每日配额已超限（%d/%d）。请明天再试。",
			"language_error":                          "设置语言时出错。",
			"reaction_added":                          "反应 %s 已添加！",
			"hours":                                   "小时",
			"minutes":                                 "分钟",
			"seconds":                                 "秒",
			"time_remaining":                          "距离重置剩余时间: %s",
			"share_phone":                             "📱 分享电话号码",
			"cancel":                                  "❌ 取消",
			"registration_fullname_prompt":            "请输入您的全名：",
			"registration_fullname_required":          "全名是必需的。请请输入您的全名：",
			"registration_username_prompt":            "请输入您的用户名：",
			"registration_username_required":          "用户名是必需的。请请输入您的用户名：",
			"registration_email_prompt":               "请输入您的电子邮件地址：",
			"registration_invalid_email":              "电子邮件格式无效。请请输入有效的电子邮件：",
			"registration_invalid_email_detailed":     "电子邮件 %s 无效。请请输入有效的电子邮件地址：",
			"registration_invalid_usertype":           "无效的用户类型。请从可用选项中选择。",
			"registration_phone_prompt":               "请输入您的电话号码：",
			"registration_phone_required":             "电话号码是必需的。请请输入您的电话号码：",
			"registration_invalid_phone":              "无效的电话号码。请请输入有效的电话号码：",
			"registration_invalid_phone_detailed":     "电话号码 %s 对国家代码 '%s' 无效。请请输入有效的电话号码：",
			"registration_usertype_prompt":            "选择您的用户类型：",
			"registration_select_usertype":            "请从以下选项中选择您的用户类型：",
			"registration_complete":                   "注册完成！欢迎使用我们的机器人。",
			"registration_superuser_not_allowed":      "您无法注册为超级用户。超级用户数据库中未找到电话号码。",
			"registration_superuser_update_failed":    "超级用户数据更新失败: %s。请重试。",
			"registration_tams_not_allowed":           "您无法注册为TA MS。TA MS数据库中未找到电话号码。",
			"registration_tams_update_failed":         "TA MS数据更新失败: %s。请重试。",
			"registration_headms_not_allowed":         "您无法注册为Head MS。Head MS数据库中未找到电话号码。",
			"registration_headms_update_failed":       "Head MS数据更新失败: %s。请重试。",
			"registration_technicianms_not_allowed":   "您无法注册为Technician MS。电话号码 %s 未在ODOOMS中找到。",
			"registration_technicianms_update_failed": "Technician MS数据更新失败: %s。请重试。",
			"registration_chat_id_in_use":             "聊天ID已被另一个已验证用户使用。",
			"usertype_common":                         "普通用户",
			"usertype_super_user":                     "超级用户",
			"usertype_technician_ms":                  "Manage Service技术员",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "Manage Service负责人",
			"error":                                   "发生错误。请重试。",
			"registration_success_title":              "✅ 注册成功！",
			"registration_details_fullname":           "👤 全名:",
			"registration_details_username":           "👨‍💻 用户名:",
			"registration_details_email":              "📧 电子邮件:",
			"registration_details_phone":              "📱 电话:",
			"registration_details_usertype":           "🏷️ 用户类型:",
			"registration_welcome_message":            "欢迎使用我们的机器人！现在您可以使用所有功能。",
		},
		fun.LangAR: {
			"welcome":                                 "مرحباً بك في بوت Telegram! اختر خياراً:",
			"welcome_new_user":                        "👋 *مرحباً!* \n\nأنا بوت المساعد الخاص بك جاهز للمساعدة. انقر على الزر أدناه لبدء الاستخدام:",
			"help":                                    "الأوامر والخيارات المتاحة:",
			"start":                                   "ابدأ",
			"info":                                    "معلومات",
			"commands":                                "قائمة الأوامر",
			"language":                                "اللغة",
			"bot_info":                                "🤖 *معلومات البوت*\n\nهذا بوت Telegram تم إنشاؤه باستخدام Go.\n\nالميزات:\n• القوائم التفاعلية\n• معالجة الأوامر\n• استفسارات الرد\n\nاستخدم /help للمزيد من الخيارات.",
			"commands_list":                           "📋 *الأوامر المتاحة*\n\n/start - بدء البوت وعرض القائمة الرئيسية\n/help - عرض المساعدة والخيارات المتاحة\n\n*ملاحظة:* يمكنك أيضاً النقر على الأزرار أعلاه للتنقل!",
			"unknown_command":                         "أمر غير معروف. استخدم /help للأوامر المتاحة.",
			"unknown_button":                          "تم الضغط على زر غير معروف.",
			"button1":                                 "لقد ضغطت على الزر 1!",
			"button2":                                 "لقد ضغطت على الزر 2!",
			"select_language":                         "اختر اللغة / Select Language:",
			"language_set":                            "تم تغيير اللغة بنجاح إلى العربية 🇸🇦",
			"message_received":                        "تم استلام الرسالة: %s",
			"user_registration_failed":                "فشل في تسجيل المستخدم. يرجى المحاولة مرة أخرى.",
			"user_created_unverified":                 "مرحباً! تم إنشاء حسابك، لكنه يتطلب التحقق. يرجى الاتصال بالدعم الفني على %s للتحقق.",
			"database_error":                          "خطأ في قاعدة البيانات. يرجى المحاولة مرة أخرى.",
			"user_banned":                             "تم حظر حسابك. يرجى الاتصال بالمسؤول.",
			"user_unverified":                         "حسابك غير مُتحقق. يرجى الاتصال بالدعم الفني على %s للتحقق.",
			"quota_exceeded":                          "تم تجاوز الحصة اليومية (%d/%d). يرجى المحاولة غداً.",
			"language_error":                          "خطأ في تعيين اللغة.",
			"reaction_added":                          "تم إضافة التفاعل %s!",
			"hours":                                   "ساعات",
			"minutes":                                 "دقائق",
			"seconds":                                 "ثواني",
			"time_remaining":                          "الوقت المتبقي حتى إعادة التعيين: %s",
			"share_phone":                             "📱 مشاركة رقم الهاتف",
			"cancel":                                  "❌ إلغاء",
			"registration_fullname_prompt":            "أدخل اسمك الكامل:",
			"registration_fullname_required":          "الاسم الكامل مطلوب. يرجى إدخال اسمك الكامل:",
			"registration_username_prompt":            "أدخل اسم المستخدم الخاص بك:",
			"registration_username_required":          "اسم المستخدم مطلوب. يرجى إدخال اسم المستخدم الخاص بك:",
			"registration_email_prompt":               "أدخل عنوان بريدك الإلكتروني:",
			"registration_invalid_email":              "تنسيق البريد الإلكتروني غير صالح. يرجى إدخال بريد إلكتروني صالح:",
			"registration_invalid_email_detailed":     "البريد الإلكتروني %s غير صالح. يرجى إدخال عنوان بريد إلكتروني صالح:",
			"registration_invalid_usertype":           "نوع المستخدم غير صالح. يرجى الاختيار من الخيارات المتاحة.",
			"registration_phone_prompt":               "أدخل رقم هاتفك:",
			"registration_phone_required":             "رقم الهاتف مطلوب. يرجى إدخال رقم هاتفك:",
			"registration_invalid_phone":              "رقم هاتف غير صالح. يرجى إدخال رقم هاتف صالح:",
			"registration_invalid_phone_detailed":     "رقم الهاتف %s غير صالح لرمز البلد '%s'. يرجى إدخال رقم هاتف صالح:",
			"registration_usertype_prompt":            "اختر نوع المستخدم الخاص بك:",
			"registration_select_usertype":            "يرجى اختيار نوع المستخدم الخاص بك من الخيارات أدناه:",
			"registration_complete":                   "اكتمل التسجيل! مرحباً بك في بوتنا.",
			"registration_superuser_not_allowed":      "لا يمكنك التسجيل كمستخدم فائق. رقم الهاتف غير موجود في قاعدة بيانات المستخدم الفائق.",
			"registration_superuser_update_failed":    "فشل في تحديث بيانات المستخدم الفائق: %s. يرجى المحاولة مرة أخرى.",
			"registration_tams_not_allowed":           "لا يمكنك التسجيل كـTA MS. رقم الهاتف غير موجود في قاعدة بيانات TA MS.",
			"registration_tams_update_failed":         "فشل في تحديث بيانات TA MS: %s. يرجى المحاولة مرة أخرى.",
			"registration_headms_not_allowed":         "لا يمكنك التسجيل كـHead MS. رقم الهاتف غير موجود في قاعدة بيانات Head MS.",
			"registration_headms_update_failed":       "فشل في تحديث بيانات Head MS: %s. يرجى المحاولة مرة أخرى.",
			"registration_technicianms_not_allowed":   "لا يمكنك التسجيل كـTechnician MS. رقم الهاتف %s غير موجود في ODOOMS.",
			"registration_technicianms_update_failed": "فشل في تحديث بيانات Technician MS: %s. يرجى المحاولة مرة أخرى.",
			"registration_chat_id_in_use":             "معرف الدردشة قيد الاستخدام بالفعل من قبل مستخدم آخر تم التحقق منه.",
			"usertype_common":                         "مستخدم عادي",
			"usertype_super_user":                     "مستخدم خارق",
			"usertype_technician_ms":                  "فني Manage Service",
			"usertype_tams":                           "Technical Assistance, Manage Service",
			"usertype_head_ms":                        "رئيس Manage Service",
			"error":                                   "حدث خطأ. يرجى المحاولة مرة أخرى.",
			"registration_success_title":              "✅ تم التسجيل بنجاح!",
			"registration_details_fullname":           "👤 الاسم الكامل:",
			"registration_details_username":           "👨‍💻 اسم المستخدم:",
			"registration_details_email":              "📧 البريد الإلكتروني:",
			"registration_details_phone":              "📱 الهاتف:",
			"registration_details_usertype":           "🏷️ نوع المستخدم:",
			"registration_welcome_message":            "مرحباً بك في بوتنا! يمكنك الآن استخدام جميع الوظائف.",
		},
	}

	if langMessages, exists := messages[lang]; exists {
		if msg, found := langMessages[key]; found {
			if len(args) > 0 {
				return fmt.Sprintf(msg, args...)
			}
			return msg
		}
	}
	// Fallback to Indonesia if language or key not found
	if langMessages, exists := messages[fun.DefaultLang]; exists {
		if msg, found := langMessages[key]; found {
			if len(args) > 0 {
				return fmt.Sprintf(msg, args...)
			}
			return msg
		}
	}
	return key // Return key if not found
}
