// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/scheduler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerService_RegisterJob_FullMethodName     = "/scheduler.SchedulerService/RegisterJob"
	SchedulerService_UnregisterJob_FullMethodName   = "/scheduler.SchedulerService/UnregisterJob"
	SchedulerService_ListJobs_FullMethodName        = "/scheduler.SchedulerService/ListJobs"
	SchedulerService_TriggerJob_FullMethodName      = "/scheduler.SchedulerService/TriggerJob"
	SchedulerService_GetJobStatus_FullMethodName    = "/scheduler.SchedulerService/GetJobStatus"
	SchedulerService_ReloadScheduler_FullMethodName = "/scheduler.SchedulerService/ReloadScheduler"
)

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchedulerService provides gRPC endpoints for managing scheduled jobs.
// This service allows remote management of scheduled tasks including
// registration, triggering, status checking, and configuration reloading.
//
// The scheduler service runs independently from the API service, providing
// better isolation and scalability for scheduled job execution.
type SchedulerServiceClient interface {
	// RegisterJob registers a new job function in the scheduler.
	// This makes the job available for scheduling and execution.
	// The job function must already exist in the codebase.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs",
	//	  "description": "Cleans up old log files"
	//	}
	RegisterJob(ctx context.Context, in *RegisterJobRequest, opts ...grpc.CallOption) (*RegisterJobResponse, error)
	// UnregisterJob removes a job from the scheduler.
	// This prevents the job from being executed in future scheduled runs.
	// The job schedule in config.yaml will remain but won't execute.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	UnregisterJob(ctx context.Context, in *UnregisterJobRequest, opts ...grpc.CallOption) (*UnregisterJobResponse, error)
	// ListJobs returns a list of all registered jobs with their details.
	// This includes job names, descriptions, schedules, and execution status.
	//
	// Example request:
	//
	//	{}
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// TriggerJob manually executes a job immediately.
	// The job runs asynchronously in the background.
	// Useful for testing or running jobs on-demand.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	TriggerJob(ctx context.Context, in *TriggerJobRequest, opts ...grpc.CallOption) (*TriggerJobResponse, error)
	// GetJobStatus retrieves the current status and details of a specific job.
	// Returns information about whether the job exists and its configuration.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	// ReloadScheduler reloads the scheduler configuration from the YAML file.
	// This allows updating job schedules without restarting the service.
	// All existing scheduled jobs are stopped and restarted with new configuration.
	//
	// Example request:
	//
	//	{}
	ReloadScheduler(ctx context.Context, in *ReloadSchedulerRequest, opts ...grpc.CallOption) (*ReloadSchedulerResponse, error)
}

type schedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerServiceClient(cc grpc.ClientConnInterface) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) RegisterJob(ctx context.Context, in *RegisterJobRequest, opts ...grpc.CallOption) (*RegisterJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_RegisterJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) UnregisterJob(ctx context.Context, in *UnregisterJobRequest, opts ...grpc.CallOption) (*UnregisterJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_UnregisterJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, SchedulerService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) TriggerJob(ctx context.Context, in *TriggerJobRequest, opts ...grpc.CallOption) (*TriggerJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_TriggerJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, SchedulerService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) ReloadScheduler(ctx context.Context, in *ReloadSchedulerRequest, opts ...grpc.CallOption) (*ReloadSchedulerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadSchedulerResponse)
	err := c.cc.Invoke(ctx, SchedulerService_ReloadScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
// All implementations must embed UnimplementedSchedulerServiceServer
// for forward compatibility.
//
// SchedulerService provides gRPC endpoints for managing scheduled jobs.
// This service allows remote management of scheduled tasks including
// registration, triggering, status checking, and configuration reloading.
//
// The scheduler service runs independently from the API service, providing
// better isolation and scalability for scheduled job execution.
type SchedulerServiceServer interface {
	// RegisterJob registers a new job function in the scheduler.
	// This makes the job available for scheduling and execution.
	// The job function must already exist in the codebase.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs",
	//	  "description": "Cleans up old log files"
	//	}
	RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error)
	// UnregisterJob removes a job from the scheduler.
	// This prevents the job from being executed in future scheduled runs.
	// The job schedule in config.yaml will remain but won't execute.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	UnregisterJob(context.Context, *UnregisterJobRequest) (*UnregisterJobResponse, error)
	// ListJobs returns a list of all registered jobs with their details.
	// This includes job names, descriptions, schedules, and execution status.
	//
	// Example request:
	//
	//	{}
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// TriggerJob manually executes a job immediately.
	// The job runs asynchronously in the background.
	// Useful for testing or running jobs on-demand.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	TriggerJob(context.Context, *TriggerJobRequest) (*TriggerJobResponse, error)
	// GetJobStatus retrieves the current status and details of a specific job.
	// Returns information about whether the job exists and its configuration.
	//
	// Example request:
	//
	//	{
	//	  "name": "cleanup-logs"
	//	}
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	// ReloadScheduler reloads the scheduler configuration from the YAML file.
	// This allows updating job schedules without restarting the service.
	// All existing scheduled jobs are stopped and restarted with new configuration.
	//
	// Example request:
	//
	//	{}
	ReloadScheduler(context.Context, *ReloadSchedulerRequest) (*ReloadSchedulerResponse, error)
	mustEmbedUnimplementedSchedulerServiceServer()
}

// UnimplementedSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServiceServer struct{}

func (UnimplementedSchedulerServiceServer) RegisterJob(context.Context, *RegisterJobRequest) (*RegisterJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterJob not implemented")
}
func (UnimplementedSchedulerServiceServer) UnregisterJob(context.Context, *UnregisterJobRequest) (*UnregisterJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterJob not implemented")
}
func (UnimplementedSchedulerServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedSchedulerServiceServer) TriggerJob(context.Context, *TriggerJobRequest) (*TriggerJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerJob not implemented")
}
func (UnimplementedSchedulerServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedSchedulerServiceServer) ReloadScheduler(context.Context, *ReloadSchedulerRequest) (*ReloadSchedulerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadScheduler not implemented")
}
func (UnimplementedSchedulerServiceServer) mustEmbedUnimplementedSchedulerServiceServer() {}
func (UnimplementedSchedulerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServiceServer will
// result in compilation errors.
type UnsafeSchedulerServiceServer interface {
	mustEmbedUnimplementedSchedulerServiceServer()
}

func RegisterSchedulerServiceServer(s grpc.ServiceRegistrar, srv SchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerService_ServiceDesc, srv)
}

func _SchedulerService_RegisterJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).RegisterJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_RegisterJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).RegisterJob(ctx, req.(*RegisterJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_UnregisterJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).UnregisterJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_UnregisterJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).UnregisterJob(ctx, req.(*UnregisterJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_TriggerJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).TriggerJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_TriggerJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).TriggerJob(ctx, req.(*TriggerJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_ReloadScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadSchedulerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ReloadScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_ReloadScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ReloadScheduler(ctx, req.(*ReloadSchedulerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerService_ServiceDesc is the grpc.ServiceDesc for SchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterJob",
			Handler:    _SchedulerService_RegisterJob_Handler,
		},
		{
			MethodName: "UnregisterJob",
			Handler:    _SchedulerService_UnregisterJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _SchedulerService_ListJobs_Handler,
		},
		{
			MethodName: "TriggerJob",
			Handler:    _SchedulerService_TriggerJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _SchedulerService_GetJobStatus_Handler,
		},
		{
			MethodName: "ReloadScheduler",
			Handler:    _SchedulerService_ReloadScheduler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scheduler.proto",
}
