// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterJobRequest contains information needed to register a new job.
type RegisterJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier for the job.
	// Must match the job name in config.yaml and the registered job function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description provides human-readable information about the job's purpose.
	// Optional field for documentation purposes.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterJobRequest) Reset() {
	*x = RegisterJobRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterJobRequest) ProtoMessage() {}

func (x *RegisterJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterJobRequest.ProtoReflect.Descriptor instead.
func (*RegisterJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// RegisterJobResponse indicates the result of job registration.
type RegisterJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the job was registered successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the registration result.
	// Contains error details if success is false.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterJobResponse) Reset() {
	*x = RegisterJobResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterJobResponse) ProtoMessage() {}

func (x *RegisterJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterJobResponse.ProtoReflect.Descriptor instead.
func (*RegisterJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UnregisterJobRequest specifies which job to remove from the scheduler.
type UnregisterJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the job to unregister.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterJobRequest) Reset() {
	*x = UnregisterJobRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterJobRequest) ProtoMessage() {}

func (x *UnregisterJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterJobRequest.ProtoReflect.Descriptor instead.
func (*UnregisterJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UnregisterJobResponse indicates the result of job unregistration.
type UnregisterJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the job was unregistered successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the unregistration result.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterJobResponse) Reset() {
	*x = UnregisterJobResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterJobResponse) ProtoMessage() {}

func (x *UnregisterJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterJobResponse.ProtoReflect.Descriptor instead.
func (*UnregisterJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListJobsRequest is an empty message for listing all jobs.
// No parameters are required to list all registered jobs.
type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

// JobInfo contains detailed information about a scheduled job.
type JobInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the job.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description provides information about the job's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// schedule describes when the job runs (e.g., "every 5m", "daily at 09:00").
	Schedule string `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// last_run is the timestamp of the job's most recent execution.
	// Format: RFC3339 (e.g., "2025-12-22T10:30:00Z")
	// Empty if the job has never run.
	LastRun string `protobuf:"bytes,4,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	// next_run is the timestamp of the job's next scheduled execution.
	// Format: RFC3339 (e.g., "2025-12-22T11:30:00Z")
	// Empty if the job is not scheduled.
	NextRun string `protobuf:"bytes,5,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	// is_running indicates whether the job is currently executing.
	IsRunning     bool `protobuf:"varint,6,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *JobInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobInfo) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *JobInfo) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *JobInfo) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *JobInfo) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

// ListJobsResponse contains a list of all registered jobs.
type ListJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobs is an array of all registered job information.
	Jobs          []*JobInfo `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// TriggerJobRequest specifies which job to execute immediately.
type TriggerJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the job to trigger.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobRequest) Reset() {
	*x = TriggerJobRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobRequest) ProtoMessage() {}

func (x *TriggerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobRequest.ProtoReflect.Descriptor instead.
func (*TriggerJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// TriggerJobResponse indicates the result of manually triggering a job.
type TriggerJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the job was triggered successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the trigger result.
	// Contains error details if the job doesn't exist or failed to start.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobResponse) Reset() {
	*x = TriggerJobResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobResponse) ProtoMessage() {}

func (x *TriggerJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobResponse.ProtoReflect.Descriptor instead.
func (*TriggerJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetJobStatusRequest specifies which job's status to retrieve.
type GetJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the job to check.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetJobStatusResponse contains the status and details of a specific job.
type GetJobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exists indicates whether a job with the requested name is registered.
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// job_info contains detailed information about the job.
	// Only populated if exists is true.
	JobInfo       *JobInfo `protobuf:"bytes,2,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobStatusResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetJobStatusResponse) GetJobInfo() *JobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

// ReloadSchedulerRequest is an empty message for reloading scheduler configuration.
// No parameters are required to reload the configuration.
type ReloadSchedulerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadSchedulerRequest) Reset() {
	*x = ReloadSchedulerRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSchedulerRequest) ProtoMessage() {}

func (x *ReloadSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSchedulerRequest.ProtoReflect.Descriptor instead.
func (*ReloadSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

// ReloadSchedulerResponse indicates the result of reloading the scheduler.
type ReloadSchedulerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the scheduler was reloaded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the reload result.
	// Contains error details if the reload failed.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// jobs_loaded is the number of jobs successfully loaded from configuration.
	// Only populated if success is true.
	JobsLoaded    int32 `protobuf:"varint,3,opt,name=jobs_loaded,json=jobsLoaded,proto3" json:"jobs_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadSchedulerResponse) Reset() {
	*x = ReloadSchedulerResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSchedulerResponse) ProtoMessage() {}

func (x *ReloadSchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSchedulerResponse.ProtoReflect.Descriptor instead.
func (*ReloadSchedulerResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadSchedulerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadSchedulerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadSchedulerResponse) GetJobsLoaded() int32 {
	if x != nil {
		return x.JobsLoaded
	}
	return 0
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"J\n" +
	"\x12RegisterJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"I\n" +
	"\x13RegisterJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x14UnregisterJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x15UnregisterJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fListJobsRequest\"\xb0\x01\n" +
	"\aJobInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x19\n" +
	"\blast_run\x18\x04 \x01(\tR\alastRun\x12\x19\n" +
	"\bnext_run\x18\x05 \x01(\tR\anextRun\x12\x1d\n" +
	"\n" +
	"is_running\x18\x06 \x01(\bR\tisRunning\":\n" +
	"\x10ListJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.scheduler.JobInfoR\x04jobs\"'\n" +
	"\x11TriggerJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x12TriggerJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x13GetJobStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"]\n" +
	"\x14GetJobStatusResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12-\n" +
	"\bjob_info\x18\x02 \x01(\v2\x12.scheduler.JobInfoR\ajobInfo\"\x18\n" +
	"\x16ReloadSchedulerRequest\"n\n" +
	"\x17ReloadSchedulerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vjobs_loaded\x18\x03 \x01(\x05R\n" +
	"jobsLoaded2\xef\x03\n" +
	"\x10SchedulerService\x12L\n" +
	"\vRegisterJob\x12\x1d.scheduler.RegisterJobRequest\x1a\x1e.scheduler.RegisterJobResponse\x12R\n" +
	"\rUnregisterJob\x12\x1f.scheduler.UnregisterJobRequest\x1a .scheduler.UnregisterJobResponse\x12C\n" +
	"\bListJobs\x12\x1a.scheduler.ListJobsRequest\x1a\x1b.scheduler.ListJobsResponse\x12I\n" +
	"\n" +
	"TriggerJob\x12\x1c.scheduler.TriggerJobRequest\x1a\x1d.scheduler.TriggerJobResponse\x12O\n" +
	"\fGetJobStatus\x12\x1e.scheduler.GetJobStatusRequest\x1a\x1f.scheduler.GetJobStatusResponse\x12X\n" +
	"\x0fReloadScheduler\x12!.scheduler.ReloadSchedulerRequest\x1a\".scheduler.ReloadSchedulerResponseB\x18Z\x16service-platform/protob\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_scheduler_proto_goTypes = []any{
	(*RegisterJobRequest)(nil),      // 0: scheduler.RegisterJobRequest
	(*RegisterJobResponse)(nil),     // 1: scheduler.RegisterJobResponse
	(*UnregisterJobRequest)(nil),    // 2: scheduler.UnregisterJobRequest
	(*UnregisterJobResponse)(nil),   // 3: scheduler.UnregisterJobResponse
	(*ListJobsRequest)(nil),         // 4: scheduler.ListJobsRequest
	(*JobInfo)(nil),                 // 5: scheduler.JobInfo
	(*ListJobsResponse)(nil),        // 6: scheduler.ListJobsResponse
	(*TriggerJobRequest)(nil),       // 7: scheduler.TriggerJobRequest
	(*TriggerJobResponse)(nil),      // 8: scheduler.TriggerJobResponse
	(*GetJobStatusRequest)(nil),     // 9: scheduler.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),    // 10: scheduler.GetJobStatusResponse
	(*ReloadSchedulerRequest)(nil),  // 11: scheduler.ReloadSchedulerRequest
	(*ReloadSchedulerResponse)(nil), // 12: scheduler.ReloadSchedulerResponse
}
var file_proto_scheduler_proto_depIdxs = []int32{
	5,  // 0: scheduler.ListJobsResponse.jobs:type_name -> scheduler.JobInfo
	5,  // 1: scheduler.GetJobStatusResponse.job_info:type_name -> scheduler.JobInfo
	0,  // 2: scheduler.SchedulerService.RegisterJob:input_type -> scheduler.RegisterJobRequest
	2,  // 3: scheduler.SchedulerService.UnregisterJob:input_type -> scheduler.UnregisterJobRequest
	4,  // 4: scheduler.SchedulerService.ListJobs:input_type -> scheduler.ListJobsRequest
	7,  // 5: scheduler.SchedulerService.TriggerJob:input_type -> scheduler.TriggerJobRequest
	9,  // 6: scheduler.SchedulerService.GetJobStatus:input_type -> scheduler.GetJobStatusRequest
	11, // 7: scheduler.SchedulerService.ReloadScheduler:input_type -> scheduler.ReloadSchedulerRequest
	1,  // 8: scheduler.SchedulerService.RegisterJob:output_type -> scheduler.RegisterJobResponse
	3,  // 9: scheduler.SchedulerService.UnregisterJob:output_type -> scheduler.UnregisterJobResponse
	6,  // 10: scheduler.SchedulerService.ListJobs:output_type -> scheduler.ListJobsResponse
	8,  // 11: scheduler.SchedulerService.TriggerJob:output_type -> scheduler.TriggerJobResponse
	10, // 12: scheduler.SchedulerService.GetJobStatus:output_type -> scheduler.GetJobStatusResponse
	12, // 13: scheduler.SchedulerService.ReloadScheduler:output_type -> scheduler.ReloadSchedulerResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
