// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/telegram.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendTelegramMessageRequest represents the payload required to send a message
// to a Telegram chat.
type SendTelegramMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id is the unique identifier for the target chat or username
	// of the target channel (in the format @channelusername).
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// text is the actual message content to be sent.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// parse_mode specifies how the text should be parsed.
	// Supported values are "Markdown" and "HTML".
	// If omitted or empty, the message is sent as plain text.
	ParseMode     string `protobuf:"bytes,3,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTelegramMessageRequest) Reset() {
	*x = SendTelegramMessageRequest{}
	mi := &file_proto_telegram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTelegramMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelegramMessageRequest) ProtoMessage() {}

func (x *SendTelegramMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelegramMessageRequest.ProtoReflect.Descriptor instead.
func (*SendTelegramMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{0}
}

func (x *SendTelegramMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendTelegramMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendTelegramMessageRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

// SendTelegramMessageResponse represents the result of a SendMessage operation.
type SendTelegramMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the message was sent successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message contains a human-readable status or error description.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// message_id is the unique identifier of the sent message in Telegram.
	// This field is set only if the message was sent successfully.
	MessageId     int64 `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTelegramMessageResponse) Reset() {
	*x = SendTelegramMessageResponse{}
	mi := &file_proto_telegram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTelegramMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelegramMessageResponse) ProtoMessage() {}

func (x *SendTelegramMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelegramMessageResponse.ProtoReflect.Descriptor instead.
func (*SendTelegramMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{1}
}

func (x *SendTelegramMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTelegramMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendTelegramMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// SendTelegramMessageWithKeyboardResponse represents the result of a SendMessageWithKeyboard operation.
type SendTelegramMessageWithKeyboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the message was sent successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message contains a human-readable status or error description.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// message_id is the unique identifier of the sent message in Telegram.
	// This field is set only if the message was sent successfully.
	MessageId     int64 `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTelegramMessageWithKeyboardResponse) Reset() {
	*x = SendTelegramMessageWithKeyboardResponse{}
	mi := &file_proto_telegram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTelegramMessageWithKeyboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelegramMessageWithKeyboardResponse) ProtoMessage() {}

func (x *SendTelegramMessageWithKeyboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelegramMessageWithKeyboardResponse.ProtoReflect.Descriptor instead.
func (*SendTelegramMessageWithKeyboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{2}
}

func (x *SendTelegramMessageWithKeyboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTelegramMessageWithKeyboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendTelegramMessageWithKeyboardResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// SendTelegramMessageWithKeyboardRequest represents a request to send a message with inline keyboard.
type SendTelegramMessageWithKeyboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id is the unique identifier for the target chat.
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// text is the message text.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// parse_mode specifies how the text should be parsed.
	ParseMode string `protobuf:"bytes,3,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	// keyboard is the inline keyboard markup.
	Keyboard      *InlineKeyboardMarkup `protobuf:"bytes,4,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTelegramMessageWithKeyboardRequest) Reset() {
	*x = SendTelegramMessageWithKeyboardRequest{}
	mi := &file_proto_telegram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTelegramMessageWithKeyboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelegramMessageWithKeyboardRequest) ProtoMessage() {}

func (x *SendTelegramMessageWithKeyboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelegramMessageWithKeyboardRequest.ProtoReflect.Descriptor instead.
func (*SendTelegramMessageWithKeyboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{3}
}

func (x *SendTelegramMessageWithKeyboardRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendTelegramMessageWithKeyboardRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendTelegramMessageWithKeyboardRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

func (x *SendTelegramMessageWithKeyboardRequest) GetKeyboard() *InlineKeyboardMarkup {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

// EditTelegramMessageRequest represents a request to edit an existing message.
type EditTelegramMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_id is the unique identifier for the target chat.
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// message_id is the ID of the message to edit.
	MessageId int64 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// text is the new message text.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// parse_mode specifies how the text should be parsed.
	ParseMode string `protobuf:"bytes,4,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	// keyboard is the new inline keyboard markup (optional).
	Keyboard      *InlineKeyboardMarkup `protobuf:"bytes,5,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTelegramMessageRequest) Reset() {
	*x = EditTelegramMessageRequest{}
	mi := &file_proto_telegram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTelegramMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTelegramMessageRequest) ProtoMessage() {}

func (x *EditTelegramMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTelegramMessageRequest.ProtoReflect.Descriptor instead.
func (*EditTelegramMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{4}
}

func (x *EditTelegramMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EditTelegramMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *EditTelegramMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EditTelegramMessageRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

func (x *EditTelegramMessageRequest) GetKeyboard() *InlineKeyboardMarkup {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

// EditTelegramMessageResponse represents the result of an EditMessage operation.
type EditTelegramMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the message was edited successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message contains a human-readable status or error description.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTelegramMessageResponse) Reset() {
	*x = EditTelegramMessageResponse{}
	mi := &file_proto_telegram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTelegramMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTelegramMessageResponse) ProtoMessage() {}

func (x *EditTelegramMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTelegramMessageResponse.ProtoReflect.Descriptor instead.
func (*EditTelegramMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{5}
}

func (x *EditTelegramMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditTelegramMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TelegramAnswerCallbackQueryRequest represents a request to answer a callback query.
type TelegramAnswerCallbackQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// callback_query_id is the unique identifier for the query to be answered.
	CallbackQueryId string `protobuf:"bytes,1,opt,name=callback_query_id,json=callbackQueryId,proto3" json:"callback_query_id,omitempty"`
	// text is the text of the notification (optional).
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// show_alert specifies whether to show an alert instead of a notification.
	ShowAlert     bool `protobuf:"varint,3,opt,name=show_alert,json=showAlert,proto3" json:"show_alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramAnswerCallbackQueryRequest) Reset() {
	*x = TelegramAnswerCallbackQueryRequest{}
	mi := &file_proto_telegram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramAnswerCallbackQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramAnswerCallbackQueryRequest) ProtoMessage() {}

func (x *TelegramAnswerCallbackQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramAnswerCallbackQueryRequest.ProtoReflect.Descriptor instead.
func (*TelegramAnswerCallbackQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{6}
}

func (x *TelegramAnswerCallbackQueryRequest) GetCallbackQueryId() string {
	if x != nil {
		return x.CallbackQueryId
	}
	return ""
}

func (x *TelegramAnswerCallbackQueryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TelegramAnswerCallbackQueryRequest) GetShowAlert() bool {
	if x != nil {
		return x.ShowAlert
	}
	return false
}

// TelegramAnswerCallbackQueryResponse represents the result of an AnswerCallbackQuery operation.
type TelegramAnswerCallbackQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the callback query was answered successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message contains a human-readable status or error description.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramAnswerCallbackQueryResponse) Reset() {
	*x = TelegramAnswerCallbackQueryResponse{}
	mi := &file_proto_telegram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramAnswerCallbackQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramAnswerCallbackQueryResponse) ProtoMessage() {}

func (x *TelegramAnswerCallbackQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramAnswerCallbackQueryResponse.ProtoReflect.Descriptor instead.
func (*TelegramAnswerCallbackQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{7}
}

func (x *TelegramAnswerCallbackQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelegramAnswerCallbackQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InlineKeyboardMarkup represents an inline keyboard markup.
type InlineKeyboardMarkup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// inline_keyboard is an array of button rows.
	InlineKeyboard []*InlineKeyboardButtonRow `protobuf:"bytes,1,rep,name=inline_keyboard,json=inlineKeyboard,proto3" json:"inline_keyboard,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InlineKeyboardMarkup) Reset() {
	*x = InlineKeyboardMarkup{}
	mi := &file_proto_telegram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardMarkup) ProtoMessage() {}

func (x *InlineKeyboardMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardMarkup.ProtoReflect.Descriptor instead.
func (*InlineKeyboardMarkup) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{8}
}

func (x *InlineKeyboardMarkup) GetInlineKeyboard() []*InlineKeyboardButtonRow {
	if x != nil {
		return x.InlineKeyboard
	}
	return nil
}

// InlineKeyboardButtonRow represents a row of inline keyboard buttons.
type InlineKeyboardButtonRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// buttons is an array of buttons in this row.
	Buttons       []*InlineKeyboardButton `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardButtonRow) Reset() {
	*x = InlineKeyboardButtonRow{}
	mi := &file_proto_telegram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardButtonRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardButtonRow) ProtoMessage() {}

func (x *InlineKeyboardButtonRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardButtonRow.ProtoReflect.Descriptor instead.
func (*InlineKeyboardButtonRow) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{9}
}

func (x *InlineKeyboardButtonRow) GetButtons() []*InlineKeyboardButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

// InlineKeyboardButton represents an inline keyboard button.
type InlineKeyboardButton struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the label text on the button.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// callback_data is the data to be sent when the button is pressed.
	CallbackData string `protobuf:"bytes,2,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	// url is the URL to be opened when the button is pressed (optional).
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardButton) Reset() {
	*x = InlineKeyboardButton{}
	mi := &file_proto_telegram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardButton) ProtoMessage() {}

func (x *InlineKeyboardButton) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardButton.ProtoReflect.Descriptor instead.
func (*InlineKeyboardButton) Descriptor() ([]byte, []int) {
	return file_proto_telegram_proto_rawDescGZIP(), []int{10}
}

func (x *InlineKeyboardButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InlineKeyboardButton) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *InlineKeyboardButton) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_telegram_proto protoreflect.FileDescriptor

const file_proto_telegram_proto_rawDesc = "" +
	"\n" +
	"\x14proto/telegram.proto\x12\x05proto\"h\n" +
	"\x1aSendTelegramMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x03 \x01(\tR\tparseMode\"p\n" +
	"\x1bSendTelegramMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"|\n" +
	"'SendTelegramMessageWithKeyboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"\xad\x01\n" +
	"&SendTelegramMessageWithKeyboardRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x03 \x01(\tR\tparseMode\x127\n" +
	"\bkeyboard\x18\x04 \x01(\v2\x1b.proto.InlineKeyboardMarkupR\bkeyboard\"\xc0\x01\n" +
	"\x1aEditTelegramMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x04 \x01(\tR\tparseMode\x127\n" +
	"\bkeyboard\x18\x05 \x01(\v2\x1b.proto.InlineKeyboardMarkupR\bkeyboard\"Q\n" +
	"\x1bEditTelegramMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\"TelegramAnswerCallbackQueryRequest\x12*\n" +
	"\x11callback_query_id\x18\x01 \x01(\tR\x0fcallbackQueryId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"show_alert\x18\x03 \x01(\bR\tshowAlert\"Y\n" +
	"#TelegramAnswerCallbackQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x14InlineKeyboardMarkup\x12G\n" +
	"\x0finline_keyboard\x18\x01 \x03(\v2\x1e.proto.InlineKeyboardButtonRowR\x0einlineKeyboard\"P\n" +
	"\x17InlineKeyboardButtonRow\x125\n" +
	"\abuttons\x18\x01 \x03(\v2\x1b.proto.InlineKeyboardButtonR\abuttons\"a\n" +
	"\x14InlineKeyboardButton\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rcallback_data\x18\x02 \x01(\tR\fcallbackData\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url2\xa5\x03\n" +
	"\x0fTelegramService\x12T\n" +
	"\vSendMessage\x12!.proto.SendTelegramMessageRequest\x1a\".proto.SendTelegramMessageResponse\x12x\n" +
	"\x17SendMessageWithKeyboard\x12-.proto.SendTelegramMessageWithKeyboardRequest\x1a..proto.SendTelegramMessageWithKeyboardResponse\x12T\n" +
	"\vEditMessage\x12!.proto.EditTelegramMessageRequest\x1a\".proto.EditTelegramMessageResponse\x12l\n" +
	"\x13AnswerCallbackQuery\x12).proto.TelegramAnswerCallbackQueryRequest\x1a*.proto.TelegramAnswerCallbackQueryResponseB\x18Z\x16service-platform/protob\x06proto3"

var (
	file_proto_telegram_proto_rawDescOnce sync.Once
	file_proto_telegram_proto_rawDescData []byte
)

func file_proto_telegram_proto_rawDescGZIP() []byte {
	file_proto_telegram_proto_rawDescOnce.Do(func() {
		file_proto_telegram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telegram_proto_rawDesc), len(file_proto_telegram_proto_rawDesc)))
	})
	return file_proto_telegram_proto_rawDescData
}

var file_proto_telegram_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_telegram_proto_goTypes = []any{
	(*SendTelegramMessageRequest)(nil),              // 0: proto.SendTelegramMessageRequest
	(*SendTelegramMessageResponse)(nil),             // 1: proto.SendTelegramMessageResponse
	(*SendTelegramMessageWithKeyboardResponse)(nil), // 2: proto.SendTelegramMessageWithKeyboardResponse
	(*SendTelegramMessageWithKeyboardRequest)(nil),  // 3: proto.SendTelegramMessageWithKeyboardRequest
	(*EditTelegramMessageRequest)(nil),              // 4: proto.EditTelegramMessageRequest
	(*EditTelegramMessageResponse)(nil),             // 5: proto.EditTelegramMessageResponse
	(*TelegramAnswerCallbackQueryRequest)(nil),      // 6: proto.TelegramAnswerCallbackQueryRequest
	(*TelegramAnswerCallbackQueryResponse)(nil),     // 7: proto.TelegramAnswerCallbackQueryResponse
	(*InlineKeyboardMarkup)(nil),                    // 8: proto.InlineKeyboardMarkup
	(*InlineKeyboardButtonRow)(nil),                 // 9: proto.InlineKeyboardButtonRow
	(*InlineKeyboardButton)(nil),                    // 10: proto.InlineKeyboardButton
}
var file_proto_telegram_proto_depIdxs = []int32{
	8,  // 0: proto.SendTelegramMessageWithKeyboardRequest.keyboard:type_name -> proto.InlineKeyboardMarkup
	8,  // 1: proto.EditTelegramMessageRequest.keyboard:type_name -> proto.InlineKeyboardMarkup
	9,  // 2: proto.InlineKeyboardMarkup.inline_keyboard:type_name -> proto.InlineKeyboardButtonRow
	10, // 3: proto.InlineKeyboardButtonRow.buttons:type_name -> proto.InlineKeyboardButton
	0,  // 4: proto.TelegramService.SendMessage:input_type -> proto.SendTelegramMessageRequest
	3,  // 5: proto.TelegramService.SendMessageWithKeyboard:input_type -> proto.SendTelegramMessageWithKeyboardRequest
	4,  // 6: proto.TelegramService.EditMessage:input_type -> proto.EditTelegramMessageRequest
	6,  // 7: proto.TelegramService.AnswerCallbackQuery:input_type -> proto.TelegramAnswerCallbackQueryRequest
	1,  // 8: proto.TelegramService.SendMessage:output_type -> proto.SendTelegramMessageResponse
	2,  // 9: proto.TelegramService.SendMessageWithKeyboard:output_type -> proto.SendTelegramMessageWithKeyboardResponse
	5,  // 10: proto.TelegramService.EditMessage:output_type -> proto.EditTelegramMessageResponse
	7,  // 11: proto.TelegramService.AnswerCallbackQuery:output_type -> proto.TelegramAnswerCallbackQueryResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_telegram_proto_init() }
func file_proto_telegram_proto_init() {
	if File_proto_telegram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telegram_proto_rawDesc), len(file_proto_telegram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telegram_proto_goTypes,
		DependencyIndexes: file_proto_telegram_proto_depIdxs,
		MessageInfos:      file_proto_telegram_proto_msgTypes,
	}.Build()
	File_proto_telegram_proto = out.File
	file_proto_telegram_proto_goTypes = nil
	file_proto_telegram_proto_depIdxs = nil
}
