// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/telegram.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramService_SendMessage_FullMethodName             = "/proto.TelegramService/SendMessage"
	TelegramService_SendMessageWithKeyboard_FullMethodName = "/proto.TelegramService/SendMessageWithKeyboard"
	TelegramService_EditMessage_FullMethodName             = "/proto.TelegramService/EditMessage"
	TelegramService_AnswerCallbackQuery_FullMethodName     = "/proto.TelegramService/AnswerCallbackQuery"
	TelegramService_SendVoice_FullMethodName               = "/proto.TelegramService/SendVoice"
	TelegramService_SendDocument_FullMethodName            = "/proto.TelegramService/SendDocument"
	TelegramService_SendPhoto_FullMethodName               = "/proto.TelegramService/SendPhoto"
	TelegramService_SendAudio_FullMethodName               = "/proto.TelegramService/SendAudio"
	TelegramService_SendVideo_FullMethodName               = "/proto.TelegramService/SendVideo"
)

// TelegramServiceClient is the client API for TelegramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelegramService provides RPC methods for interacting with the Telegram Bot API.
type TelegramServiceClient interface {
	// SendMessage sends a text message to a specific Telegram chat.
	//
	// The message can be formatted using Markdown or HTML depending on the
	// specified parse_mode.
	SendMessage(ctx context.Context, in *SendTelegramMessageRequest, opts ...grpc.CallOption) (*SendTelegramMessageResponse, error)
	// SendMessageWithKeyboard sends a message with an inline keyboard.
	SendMessageWithKeyboard(ctx context.Context, in *SendTelegramMessageWithKeyboardRequest, opts ...grpc.CallOption) (*SendTelegramMessageWithKeyboardResponse, error)
	// EditMessage edits an existing message text and/or reply markup.
	EditMessage(ctx context.Context, in *EditTelegramMessageRequest, opts ...grpc.CallOption) (*EditTelegramMessageResponse, error)
	// AnswerCallbackQuery sends an answer to a callback query.
	AnswerCallbackQuery(ctx context.Context, in *TelegramAnswerCallbackQueryRequest, opts ...grpc.CallOption) (*TelegramAnswerCallbackQueryResponse, error)
	// SendVoice sends a voice message.
	SendVoice(ctx context.Context, in *SendTelegramVoiceRequest, opts ...grpc.CallOption) (*SendTelegramVoiceResponse, error)
	// SendDocument sends a document.
	SendDocument(ctx context.Context, in *SendTelegramDocumentRequest, opts ...grpc.CallOption) (*SendTelegramDocumentResponse, error)
	// SendPhoto sends a photo.
	SendPhoto(ctx context.Context, in *SendTelegramPhotoRequest, opts ...grpc.CallOption) (*SendTelegramPhotoResponse, error)
	// SendAudio sends an audio file.
	SendAudio(ctx context.Context, in *SendTelegramAudioRequest, opts ...grpc.CallOption) (*SendTelegramAudioResponse, error)
	// SendVideo sends a video.
	SendVideo(ctx context.Context, in *SendTelegramVideoRequest, opts ...grpc.CallOption) (*SendTelegramVideoResponse, error)
}

type telegramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramServiceClient(cc grpc.ClientConnInterface) TelegramServiceClient {
	return &telegramServiceClient{cc}
}

func (c *telegramServiceClient) SendMessage(ctx context.Context, in *SendTelegramMessageRequest, opts ...grpc.CallOption) (*SendTelegramMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramMessageResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendMessageWithKeyboard(ctx context.Context, in *SendTelegramMessageWithKeyboardRequest, opts ...grpc.CallOption) (*SendTelegramMessageWithKeyboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramMessageWithKeyboardResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendMessageWithKeyboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) EditMessage(ctx context.Context, in *EditTelegramMessageRequest, opts ...grpc.CallOption) (*EditTelegramMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditTelegramMessageResponse)
	err := c.cc.Invoke(ctx, TelegramService_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) AnswerCallbackQuery(ctx context.Context, in *TelegramAnswerCallbackQueryRequest, opts ...grpc.CallOption) (*TelegramAnswerCallbackQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramAnswerCallbackQueryResponse)
	err := c.cc.Invoke(ctx, TelegramService_AnswerCallbackQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendVoice(ctx context.Context, in *SendTelegramVoiceRequest, opts ...grpc.CallOption) (*SendTelegramVoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramVoiceResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendDocument(ctx context.Context, in *SendTelegramDocumentRequest, opts ...grpc.CallOption) (*SendTelegramDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramDocumentResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendPhoto(ctx context.Context, in *SendTelegramPhotoRequest, opts ...grpc.CallOption) (*SendTelegramPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramPhotoResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendAudio(ctx context.Context, in *SendTelegramAudioRequest, opts ...grpc.CallOption) (*SendTelegramAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramAudioResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendVideo(ctx context.Context, in *SendTelegramVideoRequest, opts ...grpc.CallOption) (*SendTelegramVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTelegramVideoResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramServiceServer is the server API for TelegramService service.
// All implementations must embed UnimplementedTelegramServiceServer
// for forward compatibility.
//
// TelegramService provides RPC methods for interacting with the Telegram Bot API.
type TelegramServiceServer interface {
	// SendMessage sends a text message to a specific Telegram chat.
	//
	// The message can be formatted using Markdown or HTML depending on the
	// specified parse_mode.
	SendMessage(context.Context, *SendTelegramMessageRequest) (*SendTelegramMessageResponse, error)
	// SendMessageWithKeyboard sends a message with an inline keyboard.
	SendMessageWithKeyboard(context.Context, *SendTelegramMessageWithKeyboardRequest) (*SendTelegramMessageWithKeyboardResponse, error)
	// EditMessage edits an existing message text and/or reply markup.
	EditMessage(context.Context, *EditTelegramMessageRequest) (*EditTelegramMessageResponse, error)
	// AnswerCallbackQuery sends an answer to a callback query.
	AnswerCallbackQuery(context.Context, *TelegramAnswerCallbackQueryRequest) (*TelegramAnswerCallbackQueryResponse, error)
	// SendVoice sends a voice message.
	SendVoice(context.Context, *SendTelegramVoiceRequest) (*SendTelegramVoiceResponse, error)
	// SendDocument sends a document.
	SendDocument(context.Context, *SendTelegramDocumentRequest) (*SendTelegramDocumentResponse, error)
	// SendPhoto sends a photo.
	SendPhoto(context.Context, *SendTelegramPhotoRequest) (*SendTelegramPhotoResponse, error)
	// SendAudio sends an audio file.
	SendAudio(context.Context, *SendTelegramAudioRequest) (*SendTelegramAudioResponse, error)
	// SendVideo sends a video.
	SendVideo(context.Context, *SendTelegramVideoRequest) (*SendTelegramVideoResponse, error)
	mustEmbedUnimplementedTelegramServiceServer()
}

// UnimplementedTelegramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramServiceServer struct{}

func (UnimplementedTelegramServiceServer) SendMessage(context.Context, *SendTelegramMessageRequest) (*SendTelegramMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTelegramServiceServer) SendMessageWithKeyboard(context.Context, *SendTelegramMessageWithKeyboardRequest) (*SendTelegramMessageWithKeyboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessageWithKeyboard not implemented")
}
func (UnimplementedTelegramServiceServer) EditMessage(context.Context, *EditTelegramMessageRequest) (*EditTelegramMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedTelegramServiceServer) AnswerCallbackQuery(context.Context, *TelegramAnswerCallbackQueryRequest) (*TelegramAnswerCallbackQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerCallbackQuery not implemented")
}
func (UnimplementedTelegramServiceServer) SendVoice(context.Context, *SendTelegramVoiceRequest) (*SendTelegramVoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVoice not implemented")
}
func (UnimplementedTelegramServiceServer) SendDocument(context.Context, *SendTelegramDocumentRequest) (*SendTelegramDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDocument not implemented")
}
func (UnimplementedTelegramServiceServer) SendPhoto(context.Context, *SendTelegramPhotoRequest) (*SendTelegramPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPhoto not implemented")
}
func (UnimplementedTelegramServiceServer) SendAudio(context.Context, *SendTelegramAudioRequest) (*SendTelegramAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAudio not implemented")
}
func (UnimplementedTelegramServiceServer) SendVideo(context.Context, *SendTelegramVideoRequest) (*SendTelegramVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVideo not implemented")
}
func (UnimplementedTelegramServiceServer) mustEmbedUnimplementedTelegramServiceServer() {}
func (UnimplementedTelegramServiceServer) testEmbeddedByValue()                         {}

// UnsafeTelegramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramServiceServer will
// result in compilation errors.
type UnsafeTelegramServiceServer interface {
	mustEmbedUnimplementedTelegramServiceServer()
}

func RegisterTelegramServiceServer(s grpc.ServiceRegistrar, srv TelegramServiceServer) {
	// If the following call panics, it indicates UnimplementedTelegramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramService_ServiceDesc, srv)
}

func _TelegramService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendMessage(ctx, req.(*SendTelegramMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendMessageWithKeyboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramMessageWithKeyboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendMessageWithKeyboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendMessageWithKeyboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendMessageWithKeyboard(ctx, req.(*SendTelegramMessageWithKeyboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTelegramMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).EditMessage(ctx, req.(*EditTelegramMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_AnswerCallbackQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramAnswerCallbackQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).AnswerCallbackQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_AnswerCallbackQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).AnswerCallbackQuery(ctx, req.(*TelegramAnswerCallbackQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendVoice(ctx, req.(*SendTelegramVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendDocument(ctx, req.(*SendTelegramDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendPhoto(ctx, req.(*SendTelegramPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendAudio(ctx, req.(*SendTelegramAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTelegramVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendVideo(ctx, req.(*SendTelegramVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramService_ServiceDesc is the grpc.ServiceDesc for TelegramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TelegramService",
	HandlerType: (*TelegramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _TelegramService_SendMessage_Handler,
		},
		{
			MethodName: "SendMessageWithKeyboard",
			Handler:    _TelegramService_SendMessageWithKeyboard_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _TelegramService_EditMessage_Handler,
		},
		{
			MethodName: "AnswerCallbackQuery",
			Handler:    _TelegramService_AnswerCallbackQuery_Handler,
		},
		{
			MethodName: "SendVoice",
			Handler:    _TelegramService_SendVoice_Handler,
		},
		{
			MethodName: "SendDocument",
			Handler:    _TelegramService_SendDocument_Handler,
		},
		{
			MethodName: "SendPhoto",
			Handler:    _TelegramService_SendPhoto_Handler,
		},
		{
			MethodName: "SendAudio",
			Handler:    _TelegramService_SendAudio_Handler,
		},
		{
			MethodName: "SendVideo",
			Handler:    _TelegramService_SendVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telegram.proto",
}
