// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/twilio_whatsapp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwilioWhatsAppService_SendMessage_FullMethodName         = "/proto.TwilioWhatsAppService/SendMessage"
	TwilioWhatsAppService_SendImageMessage_FullMethodName    = "/proto.TwilioWhatsAppService/SendImageMessage"
	TwilioWhatsAppService_SendDocumentMessage_FullMethodName = "/proto.TwilioWhatsAppService/SendDocumentMessage"
	TwilioWhatsAppService_SendVideoMessage_FullMethodName    = "/proto.TwilioWhatsAppService/SendVideoMessage"
	TwilioWhatsAppService_SendAudioMessage_FullMethodName    = "/proto.TwilioWhatsAppService/SendAudioMessage"
	TwilioWhatsAppService_SendMediaMessage_FullMethodName    = "/proto.TwilioWhatsAppService/SendMediaMessage"
	TwilioWhatsAppService_GetMessageStatus_FullMethodName    = "/proto.TwilioWhatsAppService/GetMessageStatus"
)

// TwilioWhatsAppServiceClient is the client API for TwilioWhatsAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TwilioWhatsAppService provides functionality to interact with WhatsApp via Twilio
type TwilioWhatsAppServiceClient interface {
	// SendMessage sends a text message via Twilio WhatsApp
	SendMessage(ctx context.Context, in *TwilioSendMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// SendImageMessage sends an image message via Twilio
	SendImageMessage(ctx context.Context, in *TwilioSendImageMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// SendDocumentMessage sends a document message via Twilio
	SendDocumentMessage(ctx context.Context, in *TwilioSendDocumentMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// SendVideoMessage sends a video message via Twilio
	SendVideoMessage(ctx context.Context, in *TwilioSendVideoMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// SendAudioMessage sends an audio/voice message via Twilio
	SendAudioMessage(ctx context.Context, in *TwilioSendAudioMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// SendMediaMessage sends a media message (generic, supports multiple types) via Twilio - DEPRECATED: use specific methods
	SendMediaMessage(ctx context.Context, in *TwilioSendMediaMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error)
	// GetMessageStatus retrieves the delivery status of a message
	GetMessageStatus(ctx context.Context, in *TwilioGetMessageStatusRequest, opts ...grpc.CallOption) (*TwilioGetMessageStatusResponse, error)
}

type twilioWhatsAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwilioWhatsAppServiceClient(cc grpc.ClientConnInterface) TwilioWhatsAppServiceClient {
	return &twilioWhatsAppServiceClient{cc}
}

func (c *twilioWhatsAppServiceClient) SendMessage(ctx context.Context, in *TwilioSendMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) SendImageMessage(ctx context.Context, in *TwilioSendImageMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendImageMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) SendDocumentMessage(ctx context.Context, in *TwilioSendDocumentMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendDocumentMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) SendVideoMessage(ctx context.Context, in *TwilioSendVideoMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendVideoMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) SendAudioMessage(ctx context.Context, in *TwilioSendAudioMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendAudioMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) SendMediaMessage(ctx context.Context, in *TwilioSendMediaMessageRequest, opts ...grpc.CallOption) (*TwilioSendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioSendMessageResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_SendMediaMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twilioWhatsAppServiceClient) GetMessageStatus(ctx context.Context, in *TwilioGetMessageStatusRequest, opts ...grpc.CallOption) (*TwilioGetMessageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwilioGetMessageStatusResponse)
	err := c.cc.Invoke(ctx, TwilioWhatsAppService_GetMessageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwilioWhatsAppServiceServer is the server API for TwilioWhatsAppService service.
// All implementations must embed UnimplementedTwilioWhatsAppServiceServer
// for forward compatibility.
//
// TwilioWhatsAppService provides functionality to interact with WhatsApp via Twilio
type TwilioWhatsAppServiceServer interface {
	// SendMessage sends a text message via Twilio WhatsApp
	SendMessage(context.Context, *TwilioSendMessageRequest) (*TwilioSendMessageResponse, error)
	// SendImageMessage sends an image message via Twilio
	SendImageMessage(context.Context, *TwilioSendImageMessageRequest) (*TwilioSendMessageResponse, error)
	// SendDocumentMessage sends a document message via Twilio
	SendDocumentMessage(context.Context, *TwilioSendDocumentMessageRequest) (*TwilioSendMessageResponse, error)
	// SendVideoMessage sends a video message via Twilio
	SendVideoMessage(context.Context, *TwilioSendVideoMessageRequest) (*TwilioSendMessageResponse, error)
	// SendAudioMessage sends an audio/voice message via Twilio
	SendAudioMessage(context.Context, *TwilioSendAudioMessageRequest) (*TwilioSendMessageResponse, error)
	// SendMediaMessage sends a media message (generic, supports multiple types) via Twilio - DEPRECATED: use specific methods
	SendMediaMessage(context.Context, *TwilioSendMediaMessageRequest) (*TwilioSendMessageResponse, error)
	// GetMessageStatus retrieves the delivery status of a message
	GetMessageStatus(context.Context, *TwilioGetMessageStatusRequest) (*TwilioGetMessageStatusResponse, error)
	mustEmbedUnimplementedTwilioWhatsAppServiceServer()
}

// UnimplementedTwilioWhatsAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwilioWhatsAppServiceServer struct{}

func (UnimplementedTwilioWhatsAppServiceServer) SendMessage(context.Context, *TwilioSendMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) SendImageMessage(context.Context, *TwilioSendImageMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendImageMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) SendDocumentMessage(context.Context, *TwilioSendDocumentMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDocumentMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) SendVideoMessage(context.Context, *TwilioSendVideoMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVideoMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) SendAudioMessage(context.Context, *TwilioSendAudioMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAudioMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) SendMediaMessage(context.Context, *TwilioSendMediaMessageRequest) (*TwilioSendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMediaMessage not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) GetMessageStatus(context.Context, *TwilioGetMessageStatusRequest) (*TwilioGetMessageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageStatus not implemented")
}
func (UnimplementedTwilioWhatsAppServiceServer) mustEmbedUnimplementedTwilioWhatsAppServiceServer() {}
func (UnimplementedTwilioWhatsAppServiceServer) testEmbeddedByValue()                               {}

// UnsafeTwilioWhatsAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwilioWhatsAppServiceServer will
// result in compilation errors.
type UnsafeTwilioWhatsAppServiceServer interface {
	mustEmbedUnimplementedTwilioWhatsAppServiceServer()
}

func RegisterTwilioWhatsAppServiceServer(s grpc.ServiceRegistrar, srv TwilioWhatsAppServiceServer) {
	// If the following call panics, it indicates UnimplementedTwilioWhatsAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwilioWhatsAppService_ServiceDesc, srv)
}

func _TwilioWhatsAppService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendMessage(ctx, req.(*TwilioSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_SendImageMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendImageMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendImageMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendImageMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendImageMessage(ctx, req.(*TwilioSendImageMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_SendDocumentMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendDocumentMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendDocumentMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendDocumentMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendDocumentMessage(ctx, req.(*TwilioSendDocumentMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_SendVideoMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendVideoMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendVideoMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendVideoMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendVideoMessage(ctx, req.(*TwilioSendVideoMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_SendAudioMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendAudioMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendAudioMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendAudioMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendAudioMessage(ctx, req.(*TwilioSendAudioMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_SendMediaMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioSendMediaMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).SendMediaMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_SendMediaMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).SendMediaMessage(ctx, req.(*TwilioSendMediaMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwilioWhatsAppService_GetMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwilioGetMessageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwilioWhatsAppServiceServer).GetMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwilioWhatsAppService_GetMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwilioWhatsAppServiceServer).GetMessageStatus(ctx, req.(*TwilioGetMessageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TwilioWhatsAppService_ServiceDesc is the grpc.ServiceDesc for TwilioWhatsAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwilioWhatsAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TwilioWhatsAppService",
	HandlerType: (*TwilioWhatsAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _TwilioWhatsAppService_SendMessage_Handler,
		},
		{
			MethodName: "SendImageMessage",
			Handler:    _TwilioWhatsAppService_SendImageMessage_Handler,
		},
		{
			MethodName: "SendDocumentMessage",
			Handler:    _TwilioWhatsAppService_SendDocumentMessage_Handler,
		},
		{
			MethodName: "SendVideoMessage",
			Handler:    _TwilioWhatsAppService_SendVideoMessage_Handler,
		},
		{
			MethodName: "SendAudioMessage",
			Handler:    _TwilioWhatsAppService_SendAudioMessage_Handler,
		},
		{
			MethodName: "SendMediaMessage",
			Handler:    _TwilioWhatsAppService_SendMediaMessage_Handler,
		},
		{
			MethodName: "GetMessageStatus",
			Handler:    _TwilioWhatsAppService_GetMessageStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/twilio_whatsapp.proto",
}
