// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/twilio_whatsapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TwilioSendMessageRequest is the request to send a text message via Twilio
type TwilioSendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Message content
	Body          string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendMessageRequest) Reset() {
	*x = TwilioSendMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendMessageRequest) ProtoMessage() {}

func (x *TwilioSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *TwilioSendMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// TwilioSendImageMessageRequest is the request to send an image message via Twilio
type TwilioSendImageMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// URL of the image file (JPG, JPEG, PNG)
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Optional caption for the image
	Caption       string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendImageMessageRequest) Reset() {
	*x = TwilioSendImageMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendImageMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendImageMessageRequest) ProtoMessage() {}

func (x *TwilioSendImageMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendImageMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendImageMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *TwilioSendImageMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendImageMessageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TwilioSendImageMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

// TwilioSendDocumentMessageRequest is the request to send a document message via Twilio
type TwilioSendDocumentMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// URL of the document file (PDF, DOC, etc. - max 16MB)
	DocumentUrl string `protobuf:"bytes,2,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	// Optional caption/filename for the document
	Caption       string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendDocumentMessageRequest) Reset() {
	*x = TwilioSendDocumentMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendDocumentMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendDocumentMessageRequest) ProtoMessage() {}

func (x *TwilioSendDocumentMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendDocumentMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendDocumentMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *TwilioSendDocumentMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendDocumentMessageRequest) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *TwilioSendDocumentMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

// TwilioSendVideoMessageRequest is the request to send a video message via Twilio
type TwilioSendVideoMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// URL of the video file (MP4, MOV, etc.)
	VideoUrl string `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	// Optional caption for the video
	Caption       string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendVideoMessageRequest) Reset() {
	*x = TwilioSendVideoMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendVideoMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendVideoMessageRequest) ProtoMessage() {}

func (x *TwilioSendVideoMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendVideoMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendVideoMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *TwilioSendVideoMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendVideoMessageRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *TwilioSendVideoMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

// TwilioSendAudioMessageRequest is the request to send an audio/voice message via Twilio
type TwilioSendAudioMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// URL of the audio file (MP3, WAV, OGG, etc.)
	AudioUrl      string `protobuf:"bytes,2,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendAudioMessageRequest) Reset() {
	*x = TwilioSendAudioMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendAudioMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendAudioMessageRequest) ProtoMessage() {}

func (x *TwilioSendAudioMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendAudioMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendAudioMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *TwilioSendAudioMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendAudioMessageRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

// TwilioSendMediaMessageRequest is the request to send a generic media message via Twilio - DEPRECATED
type TwilioSendMediaMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to send the message to (e.g., "+1234567890")
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// URL of the media file
	MediaUrl string `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	// Optional caption for the media
	Caption string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	// Media type: image, video, document, audio
	MediaType     string `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendMediaMessageRequest) Reset() {
	*x = TwilioSendMediaMessageRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendMediaMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendMediaMessageRequest) ProtoMessage() {}

func (x *TwilioSendMediaMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendMediaMessageRequest.ProtoReflect.Descriptor instead.
func (*TwilioSendMediaMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *TwilioSendMediaMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioSendMediaMessageRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *TwilioSendMediaMessageRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *TwilioSendMediaMessageRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

// TwilioSendMessageResponse is the response from sending a message via Twilio
type TwilioSendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the message was sent successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Twilio Message SID (unique identifier)
	MessageSid string `protobuf:"bytes,3,opt,name=message_sid,json=messageSid,proto3" json:"message_sid,omitempty"`
	// Timestamp when the message was sent
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Phone number the message was sent to
	To            string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioSendMessageResponse) Reset() {
	*x = TwilioSendMessageResponse{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioSendMessageResponse) ProtoMessage() {}

func (x *TwilioSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioSendMessageResponse.ProtoReflect.Descriptor instead.
func (*TwilioSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *TwilioSendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TwilioSendMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TwilioSendMessageResponse) GetMessageSid() string {
	if x != nil {
		return x.MessageSid
	}
	return ""
}

func (x *TwilioSendMessageResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TwilioSendMessageResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// TwilioGetMessageStatusRequest is the request to get message status
type TwilioGetMessageStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Twilio Message SID to check status for
	MessageSid    string `protobuf:"bytes,1,opt,name=message_sid,json=messageSid,proto3" json:"message_sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioGetMessageStatusRequest) Reset() {
	*x = TwilioGetMessageStatusRequest{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioGetMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioGetMessageStatusRequest) ProtoMessage() {}

func (x *TwilioGetMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioGetMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*TwilioGetMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *TwilioGetMessageStatusRequest) GetMessageSid() string {
	if x != nil {
		return x.MessageSid
	}
	return ""
}

// TwilioGetMessageStatusResponse is the response with message status
type TwilioGetMessageStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status: queued, sending, sent, failed, delivered, undelivered, receiving, received, read
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Message SID
	MessageSid string `protobuf:"bytes,2,opt,name=message_sid,json=messageSid,proto3" json:"message_sid,omitempty"`
	// Error code (if any)
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Error message (if any)
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Account SID
	AccountSid string `protobuf:"bytes,5,opt,name=account_sid,json=accountSid,proto3" json:"account_sid,omitempty"`
	// Phone number the message was sent to
	To string `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	// Timestamp of the last status update
	Timestamp     string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwilioGetMessageStatusResponse) Reset() {
	*x = TwilioGetMessageStatusResponse{}
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwilioGetMessageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwilioGetMessageStatusResponse) ProtoMessage() {}

func (x *TwilioGetMessageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_twilio_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwilioGetMessageStatusResponse.ProtoReflect.Descriptor instead.
func (*TwilioGetMessageStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_twilio_whatsapp_proto_rawDescGZIP(), []int{8}
}

func (x *TwilioGetMessageStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetMessageSid() string {
	if x != nil {
		return x.MessageSid
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetAccountSid() string {
	if x != nil {
		return x.AccountSid
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TwilioGetMessageStatusResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_twilio_whatsapp_proto protoreflect.FileDescriptor

const file_proto_twilio_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/twilio_whatsapp.proto\x12\x05proto\">\n" +
	"\x18TwilioSendMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"f\n" +
	"\x1dTwilioSendImageMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\"o\n" +
	" TwilioSendDocumentMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12!\n" +
	"\fdocument_url\x18\x02 \x01(\tR\vdocumentUrl\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\"f\n" +
	"\x1dTwilioSendVideoMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\"L\n" +
	"\x1dTwilioSendAudioMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1b\n" +
	"\taudio_url\x18\x02 \x01(\tR\baudioUrl\"\x85\x01\n" +
	"\x1dTwilioSendMediaMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\"\x9e\x01\n" +
	"\x19TwilioSendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vmessage_sid\x18\x03 \x01(\tR\n" +
	"messageSid\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"@\n" +
	"\x1dTwilioGetMessageStatusRequest\x12\x1f\n" +
	"\vmessage_sid\x18\x01 \x01(\tR\n" +
	"messageSid\"\xec\x01\n" +
	"\x1eTwilioGetMessageStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vmessage_sid\x18\x02 \x01(\tR\n" +
	"messageSid\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vaccount_sid\x18\x05 \x01(\tR\n" +
	"accountSid\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp2\x9c\x05\n" +
	"\x15TwilioWhatsAppService\x12P\n" +
	"\vSendMessage\x12\x1f.proto.TwilioSendMessageRequest\x1a .proto.TwilioSendMessageResponse\x12Z\n" +
	"\x10SendImageMessage\x12$.proto.TwilioSendImageMessageRequest\x1a .proto.TwilioSendMessageResponse\x12`\n" +
	"\x13SendDocumentMessage\x12'.proto.TwilioSendDocumentMessageRequest\x1a .proto.TwilioSendMessageResponse\x12Z\n" +
	"\x10SendVideoMessage\x12$.proto.TwilioSendVideoMessageRequest\x1a .proto.TwilioSendMessageResponse\x12Z\n" +
	"\x10SendAudioMessage\x12$.proto.TwilioSendAudioMessageRequest\x1a .proto.TwilioSendMessageResponse\x12Z\n" +
	"\x10SendMediaMessage\x12$.proto.TwilioSendMediaMessageRequest\x1a .proto.TwilioSendMessageResponse\x12_\n" +
	"\x10GetMessageStatus\x12$.proto.TwilioGetMessageStatusRequest\x1a%.proto.TwilioGetMessageStatusResponseB\x18Z\x16service-platform/protob\x06proto3"

var (
	file_proto_twilio_whatsapp_proto_rawDescOnce sync.Once
	file_proto_twilio_whatsapp_proto_rawDescData []byte
)

func file_proto_twilio_whatsapp_proto_rawDescGZIP() []byte {
	file_proto_twilio_whatsapp_proto_rawDescOnce.Do(func() {
		file_proto_twilio_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_twilio_whatsapp_proto_rawDesc), len(file_proto_twilio_whatsapp_proto_rawDesc)))
	})
	return file_proto_twilio_whatsapp_proto_rawDescData
}

var file_proto_twilio_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_twilio_whatsapp_proto_goTypes = []any{
	(*TwilioSendMessageRequest)(nil),         // 0: proto.TwilioSendMessageRequest
	(*TwilioSendImageMessageRequest)(nil),    // 1: proto.TwilioSendImageMessageRequest
	(*TwilioSendDocumentMessageRequest)(nil), // 2: proto.TwilioSendDocumentMessageRequest
	(*TwilioSendVideoMessageRequest)(nil),    // 3: proto.TwilioSendVideoMessageRequest
	(*TwilioSendAudioMessageRequest)(nil),    // 4: proto.TwilioSendAudioMessageRequest
	(*TwilioSendMediaMessageRequest)(nil),    // 5: proto.TwilioSendMediaMessageRequest
	(*TwilioSendMessageResponse)(nil),        // 6: proto.TwilioSendMessageResponse
	(*TwilioGetMessageStatusRequest)(nil),    // 7: proto.TwilioGetMessageStatusRequest
	(*TwilioGetMessageStatusResponse)(nil),   // 8: proto.TwilioGetMessageStatusResponse
}
var file_proto_twilio_whatsapp_proto_depIdxs = []int32{
	0, // 0: proto.TwilioWhatsAppService.SendMessage:input_type -> proto.TwilioSendMessageRequest
	1, // 1: proto.TwilioWhatsAppService.SendImageMessage:input_type -> proto.TwilioSendImageMessageRequest
	2, // 2: proto.TwilioWhatsAppService.SendDocumentMessage:input_type -> proto.TwilioSendDocumentMessageRequest
	3, // 3: proto.TwilioWhatsAppService.SendVideoMessage:input_type -> proto.TwilioSendVideoMessageRequest
	4, // 4: proto.TwilioWhatsAppService.SendAudioMessage:input_type -> proto.TwilioSendAudioMessageRequest
	5, // 5: proto.TwilioWhatsAppService.SendMediaMessage:input_type -> proto.TwilioSendMediaMessageRequest
	7, // 6: proto.TwilioWhatsAppService.GetMessageStatus:input_type -> proto.TwilioGetMessageStatusRequest
	6, // 7: proto.TwilioWhatsAppService.SendMessage:output_type -> proto.TwilioSendMessageResponse
	6, // 8: proto.TwilioWhatsAppService.SendImageMessage:output_type -> proto.TwilioSendMessageResponse
	6, // 9: proto.TwilioWhatsAppService.SendDocumentMessage:output_type -> proto.TwilioSendMessageResponse
	6, // 10: proto.TwilioWhatsAppService.SendVideoMessage:output_type -> proto.TwilioSendMessageResponse
	6, // 11: proto.TwilioWhatsAppService.SendAudioMessage:output_type -> proto.TwilioSendMessageResponse
	6, // 12: proto.TwilioWhatsAppService.SendMediaMessage:output_type -> proto.TwilioSendMessageResponse
	8, // 13: proto.TwilioWhatsAppService.GetMessageStatus:output_type -> proto.TwilioGetMessageStatusResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_twilio_whatsapp_proto_init() }
func file_proto_twilio_whatsapp_proto_init() {
	if File_proto_twilio_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_twilio_whatsapp_proto_rawDesc), len(file_proto_twilio_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_twilio_whatsapp_proto_goTypes,
		DependencyIndexes: file_proto_twilio_whatsapp_proto_depIdxs,
		MessageInfos:      file_proto_twilio_whatsapp_proto_msgTypes,
	}.Build()
	File_proto_twilio_whatsapp_proto = out.File
	file_proto_twilio_whatsapp_proto_goTypes = nil
	file_proto_twilio_whatsapp_proto_depIdxs = nil
}
