// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/whatsapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HasContactsRequest is the request to check for contacts.
type HasContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasContactsRequest) Reset() {
	*x = HasContactsRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasContactsRequest) ProtoMessage() {}

func (x *HasContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasContactsRequest.ProtoReflect.Descriptor instead.
func (*HasContactsRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{0}
}

// HasContactsResponse contains the result of the check.
type HasContactsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Indicates if the user has at least one contact.
	HasContacts bool `protobuf:"varint,3,opt,name=has_contacts,json=hasContacts,proto3" json:"has_contacts,omitempty"`
	// The number of contacts found.
	ContactCount  int32 `protobuf:"varint,4,opt,name=contact_count,json=contactCount,proto3" json:"contact_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasContactsResponse) Reset() {
	*x = HasContactsResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasContactsResponse) ProtoMessage() {}

func (x *HasContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasContactsResponse.ProtoReflect.Descriptor instead.
func (*HasContactsResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *HasContactsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HasContactsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HasContactsResponse) GetHasContacts() bool {
	if x != nil {
		return x.HasContacts
	}
	return false
}

func (x *HasContactsResponse) GetContactCount() int32 {
	if x != nil {
		return x.ContactCount
	}
	return 0
}

// GetJoinedGroupsRequest is the request for retrieving joined groups.
type GetJoinedGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinedGroupsRequest) Reset() {
	*x = GetJoinedGroupsRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinedGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedGroupsRequest) ProtoMessage() {}

func (x *GetJoinedGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetJoinedGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{2}
}

// GetJoinedGroupsResponse contains the list of joined groups.
type GetJoinedGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// List of groups the user is a participant of.
	Groups        []*GroupInfo `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinedGroupsResponse) Reset() {
	*x = GetJoinedGroupsResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinedGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedGroupsResponse) ProtoMessage() {}

func (x *GetJoinedGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetJoinedGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *GetJoinedGroupsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetJoinedGroupsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetJoinedGroupsResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

// GroupInfo contains details about a WhatsApp group.
type GroupInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the group.
	Jid string `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	// JID of the group owner.
	OwnerJid string `protobuf:"bytes,2,opt,name=owner_jid,json=ownerJid,proto3" json:"owner_jid,omitempty"`
	// Name of the group.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Topic of the group.
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// Timestamp when the topic was set.
	TopicSetAt int64 `protobuf:"varint,5,opt,name=topic_set_at,json=topicSetAt,proto3" json:"topic_set_at,omitempty"`
	// JID of the user who set the topic.
	TopicSetBy string `protobuf:"bytes,6,opt,name=topic_set_by,json=topicSetBy,proto3" json:"topic_set_by,omitempty"`
	// JID of the parent group (if applicable).
	LinkedParentJid string `protobuf:"bytes,7,opt,name=linked_parent_jid,json=linkedParentJid,proto3" json:"linked_parent_jid,omitempty"`
	// Indicates if this is a default sub-group.
	IsDefaultSubGroup bool `protobuf:"varint,8,opt,name=is_default_sub_group,json=isDefaultSubGroup,proto3" json:"is_default_sub_group,omitempty"`
	// Indicates if this is a parent group (community).
	IsParent bool `protobuf:"varint,9,opt,name=is_parent,json=isParent,proto3" json:"is_parent,omitempty"`
	// List of participants in the group.
	Participants  []*GroupParticipant `protobuf:"bytes,10,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *GroupInfo) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *GroupInfo) GetOwnerJid() string {
	if x != nil {
		return x.OwnerJid
	}
	return ""
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GroupInfo) GetTopicSetAt() int64 {
	if x != nil {
		return x.TopicSetAt
	}
	return 0
}

func (x *GroupInfo) GetTopicSetBy() string {
	if x != nil {
		return x.TopicSetBy
	}
	return ""
}

func (x *GroupInfo) GetLinkedParentJid() string {
	if x != nil {
		return x.LinkedParentJid
	}
	return ""
}

func (x *GroupInfo) GetIsDefaultSubGroup() bool {
	if x != nil {
		return x.IsDefaultSubGroup
	}
	return false
}

func (x *GroupInfo) GetIsParent() bool {
	if x != nil {
		return x.IsParent
	}
	return false
}

func (x *GroupInfo) GetParticipants() []*GroupParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

// IsOnWhatsAppRequest is the request to check if numbers are on WhatsApp.
type IsOnWhatsAppRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of phone numbers to check.
	PhoneNumbers  []string `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnWhatsAppRequest) Reset() {
	*x = IsOnWhatsAppRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnWhatsAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnWhatsAppRequest) ProtoMessage() {}

func (x *IsOnWhatsAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnWhatsAppRequest.ProtoReflect.Descriptor instead.
func (*IsOnWhatsAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *IsOnWhatsAppRequest) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

// IsOnWhatsAppResponse contains the results of the check.
type IsOnWhatsAppResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// List of results for each phone number.
	Results       []*OnWhatsAppResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnWhatsAppResponse) Reset() {
	*x = IsOnWhatsAppResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnWhatsAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnWhatsAppResponse) ProtoMessage() {}

func (x *IsOnWhatsAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnWhatsAppResponse.ProtoReflect.Descriptor instead.
func (*IsOnWhatsAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *IsOnWhatsAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IsOnWhatsAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IsOnWhatsAppResponse) GetResults() []*OnWhatsAppResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// OnWhatsAppResult contains the registration status of a single number.
type OnWhatsAppResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The phone number that was queried.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The JID of the user if registered.
	Jid string `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	// Indicates if the number is registered on WhatsApp.
	IsRegistered  bool `protobuf:"varint,3,opt,name=is_registered,json=isRegistered,proto3" json:"is_registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnWhatsAppResult) Reset() {
	*x = OnWhatsAppResult{}
	mi := &file_proto_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnWhatsAppResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnWhatsAppResult) ProtoMessage() {}

func (x *OnWhatsAppResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnWhatsAppResult.ProtoReflect.Descriptor instead.
func (*OnWhatsAppResult) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *OnWhatsAppResult) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *OnWhatsAppResult) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *OnWhatsAppResult) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

// GetMeRequest is the request to get current user info.
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{8}
}

// GetMeResponse contains the current user's info.
type GetMeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JID of the current user.
	Jid           string `protobuf:"bytes,3,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMeResponse) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

// GetGroupInfoRequest is the request to get info about a specific group.
type GetGroupInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the group to retrieve info for.
	GroupJid      string `protobuf:"bytes,1,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupInfoRequest) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

// GetGroupInfoResponse contains the group information.
type GetGroupInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Name of the group.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// List of participants in the group.
	Participants  []*GroupParticipant `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResponse) Reset() {
	*x = GetGroupInfoResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResponse) ProtoMessage() {}

func (x *GetGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{11}
}

func (x *GetGroupInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetGroupInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupInfoResponse) GetParticipants() []*GroupParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

// GroupParticipant contains details about a group member.
type GroupParticipant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the participant.
	Jid string `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	// Indicates if the participant is an admin.
	IsAdmin bool `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	// Indicates if the participant is a super admin.
	IsSuperAdmin bool `protobuf:"varint,3,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	// LID (Linked Device ID) of the participant.
	Lid string `protobuf:"bytes,4,opt,name=lid,proto3" json:"lid,omitempty"`
	// Display name of the participant.
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// URL of the participant's profile picture.
	ProfilePictureUrl string `protobuf:"bytes,6,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	// Phone number of the participant.
	PhoneNumber   string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupParticipant) Reset() {
	*x = GroupParticipant{}
	mi := &file_proto_whatsapp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupParticipant) ProtoMessage() {}

func (x *GroupParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupParticipant.ProtoReflect.Descriptor instead.
func (*GroupParticipant) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{12}
}

func (x *GroupParticipant) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *GroupParticipant) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *GroupParticipant) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *GroupParticipant) GetLid() string {
	if x != nil {
		return x.Lid
	}
	return ""
}

func (x *GroupParticipant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GroupParticipant) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *GroupParticipant) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// RefreshQRRequest is the request to refresh the QR code.
type RefreshQRRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number associated with the request (optional).
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshQRRequest) Reset() {
	*x = RefreshQRRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshQRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshQRRequest) ProtoMessage() {}

func (x *RefreshQRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshQRRequest.ProtoReflect.Descriptor instead.
func (*RefreshQRRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshQRRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// WALogoutRequest is the request to logout from WhatsApp.
type WALogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to logout (optional).
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALogoutRequest) Reset() {
	*x = WALogoutRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALogoutRequest) ProtoMessage() {}

func (x *WALogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALogoutRequest.ProtoReflect.Descriptor instead.
func (*WALogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{14}
}

func (x *WALogoutRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// WALogoutResponse contains the result of the logout operation.
type WALogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the logout was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALogoutResponse) Reset() {
	*x = WALogoutResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALogoutResponse) ProtoMessage() {}

func (x *WALogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALogoutResponse.ProtoReflect.Descriptor instead.
func (*WALogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{15}
}

func (x *WALogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WALogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateStatusRequest is the request to create a status.
type CreateStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content of the status.
	Content *MessageContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Optional background color for text status (hex code).
	BackgroundColor string `protobuf:"bytes,2,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	// Optional font for text status.
	Font int32 `protobuf:"varint,3,opt,name=font,proto3" json:"font,omitempty"`
	// Optional target JIDs (if you want to restrict who sees it).
	TargetJids    []string `protobuf:"bytes,4,rep,name=target_jids,json=targetJids,proto3" json:"target_jids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatusRequest) Reset() {
	*x = CreateStatusRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatusRequest) ProtoMessage() {}

func (x *CreateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatusRequest.ProtoReflect.Descriptor instead.
func (*CreateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{16}
}

func (x *CreateStatusRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateStatusRequest) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *CreateStatusRequest) GetFont() int32 {
	if x != nil {
		return x.Font
	}
	return 0
}

func (x *CreateStatusRequest) GetTargetJids() []string {
	if x != nil {
		return x.TargetJids
	}
	return nil
}

// CreateStatusResponse contains the result of creating a status.
type CreateStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID of the created status message.
	StatusId      string `protobuf:"bytes,3,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatusResponse) Reset() {
	*x = CreateStatusResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatusResponse) ProtoMessage() {}

func (x *CreateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatusResponse.ProtoReflect.Descriptor instead.
func (*CreateStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{17}
}

func (x *CreateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateStatusResponse) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

// SendMessageRequest is the request to send a message.
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the recipient (user or group).
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Content of the message.
	Content       *MessageContent `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{18}
}

func (x *SendMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMessageRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

// MessageContent defines the types of content a message can have.
type MessageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ContentType:
	//
	//	*MessageContent_Text
	//	*MessageContent_Media
	//	*MessageContent_Location
	//	*MessageContent_LiveLocation
	//	*MessageContent_Poll
	//	*MessageContent_Contact
	ContentType   isMessageContent_ContentType `protobuf_oneof:"content_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{19}
}

func (x *MessageContent) GetContentType() isMessageContent_ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *MessageContent) GetText() string {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MessageContent) GetMedia() *MediaContent {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *MessageContent) GetLocation() *LocationContent {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *MessageContent) GetLiveLocation() *LiveLocationContent {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_LiveLocation); ok {
			return x.LiveLocation
		}
	}
	return nil
}

func (x *MessageContent) GetPoll() *PollContent {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_Poll); ok {
			return x.Poll
		}
	}
	return nil
}

func (x *MessageContent) GetContact() *ContactContent {
	if x != nil {
		if x, ok := x.ContentType.(*MessageContent_Contact); ok {
			return x.Contact
		}
	}
	return nil
}

type isMessageContent_ContentType interface {
	isMessageContent_ContentType()
}

type MessageContent_Text struct {
	// Text content.
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageContent_Media struct {
	// Media content (image, video, audio, document, sticker).
	Media *MediaContent `protobuf:"bytes,2,opt,name=media,proto3,oneof"`
}

type MessageContent_Location struct {
	// Location content.
	Location *LocationContent `protobuf:"bytes,3,opt,name=location,proto3,oneof"`
}

type MessageContent_LiveLocation struct {
	// Live location content.
	LiveLocation *LiveLocationContent `protobuf:"bytes,4,opt,name=live_location,json=liveLocation,proto3,oneof"`
}

type MessageContent_Poll struct {
	// Poll content.
	Poll *PollContent `protobuf:"bytes,5,opt,name=poll,proto3,oneof"`
}

type MessageContent_Contact struct {
	// Contact content.
	Contact *ContactContent `protobuf:"bytes,6,opt,name=contact,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_ContentType() {}

func (*MessageContent_Media) isMessageContent_ContentType() {}

func (*MessageContent_Location) isMessageContent_ContentType() {}

func (*MessageContent_LiveLocation) isMessageContent_ContentType() {}

func (*MessageContent_Poll) isMessageContent_ContentType() {}

func (*MessageContent_Contact) isMessageContent_ContentType() {}

// LocationContent contains location details.
type LocationContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude of the location.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude of the location.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Name of the location.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Address of the location.
	Address       string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationContent) Reset() {
	*x = LocationContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationContent) ProtoMessage() {}

func (x *LocationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationContent.ProtoReflect.Descriptor instead.
func (*LocationContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{20}
}

func (x *LocationContent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationContent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocationContent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// LiveLocationContent contains live location details.
type LiveLocationContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude of the location.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude of the location.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Accuracy of the location in meters.
	AccuracyInMeters uint32 `protobuf:"varint,3,opt,name=accuracy_in_meters,json=accuracyInMeters,proto3" json:"accuracy_in_meters,omitempty"`
	// Speed in meters per second.
	SpeedInMps uint32 `protobuf:"varint,4,opt,name=speed_in_mps,json=speedInMps,proto3" json:"speed_in_mps,omitempty"`
	// Direction in degrees clockwise from magnetic north.
	DegreesClockwiseFromMagneticNorth uint32 `protobuf:"varint,5,opt,name=degrees_clockwise_from_magnetic_north,json=degreesClockwiseFromMagneticNorth,proto3" json:"degrees_clockwise_from_magnetic_north,omitempty"`
	// Caption for the live location.
	Caption string `protobuf:"bytes,6,opt,name=caption,proto3" json:"caption,omitempty"`
	// Sequence number for location updates.
	SequenceNumber int64 `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Time offset in seconds.
	TimeOffset    uint32 `protobuf:"varint,8,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveLocationContent) Reset() {
	*x = LiveLocationContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveLocationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveLocationContent) ProtoMessage() {}

func (x *LiveLocationContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveLocationContent.ProtoReflect.Descriptor instead.
func (*LiveLocationContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{21}
}

func (x *LiveLocationContent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LiveLocationContent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LiveLocationContent) GetAccuracyInMeters() uint32 {
	if x != nil {
		return x.AccuracyInMeters
	}
	return 0
}

func (x *LiveLocationContent) GetSpeedInMps() uint32 {
	if x != nil {
		return x.SpeedInMps
	}
	return 0
}

func (x *LiveLocationContent) GetDegreesClockwiseFromMagneticNorth() uint32 {
	if x != nil {
		return x.DegreesClockwiseFromMagneticNorth
	}
	return 0
}

func (x *LiveLocationContent) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *LiveLocationContent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LiveLocationContent) GetTimeOffset() uint32 {
	if x != nil {
		return x.TimeOffset
	}
	return 0
}

// PollContent contains poll details.
type PollContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name/Question of the poll.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of options for the poll.
	Options []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	// Number of options that can be selected.
	SelectableOptionsCount uint32 `protobuf:"varint,3,opt,name=selectable_options_count,json=selectableOptionsCount,proto3" json:"selectable_options_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PollContent) Reset() {
	*x = PollContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollContent) ProtoMessage() {}

func (x *PollContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollContent.ProtoReflect.Descriptor instead.
func (*PollContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{22}
}

func (x *PollContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollContent) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollContent) GetSelectableOptionsCount() uint32 {
	if x != nil {
		return x.SelectableOptionsCount
	}
	return 0
}

// ContactContent contains contact details.
type ContactContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name of the contact.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// vCard data of the contact.
	Vcard         string `protobuf:"bytes,2,opt,name=vcard,proto3" json:"vcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactContent) Reset() {
	*x = ContactContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactContent) ProtoMessage() {}

func (x *ContactContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactContent.ProtoReflect.Descriptor instead.
func (*ContactContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{23}
}

func (x *ContactContent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ContactContent) GetVcard() string {
	if x != nil {
		return x.Vcard
	}
	return ""
}

// MediaContent contains media details.
type MediaContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of media ("image", "document", "video", "audio", "sticker").
	MediaType string `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Binary data of the media.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Filename of the media.
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	// Caption for the media.
	Caption string `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	// MIME type of the media.
	Mimetype string `protobuf:"bytes,5,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	// Indicates if the media should be view once (only for image and video).
	ViewOnce      bool `protobuf:"varint,6,opt,name=view_once,json=viewOnce,proto3" json:"view_once,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaContent) Reset() {
	*x = MediaContent{}
	mi := &file_proto_whatsapp_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaContent) ProtoMessage() {}

func (x *MediaContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaContent.ProtoReflect.Descriptor instead.
func (*MediaContent) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{24}
}

func (x *MediaContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MediaContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MediaContent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MediaContent) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *MediaContent) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *MediaContent) GetViewOnce() bool {
	if x != nil {
		return x.ViewOnce
	}
	return false
}

// SendMessageResponse contains the result of sending a message.
type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the message was sent successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID of the sent message.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Timestamp when the message was sent.
	Timestamp     string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{25}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMessageResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// GetMessagesRequest is the request to retrieve messages.
type GetMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the chat to retrieve messages from.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Maximum number of messages to retrieve.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{26}
}

func (x *GetMessagesRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetMessagesResponse contains the retrieved messages.
type GetMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of messages.
	Messages      []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{27}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Message represents a WhatsApp message.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JID of the sender.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// JID of the recipient.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Content of the message.
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Timestamp of the message.
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Type of the message ("text", "image", "document", etc.).
	MessageType string `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// Caption of the message (if applicable).
	Caption string `protobuf:"bytes,6,opt,name=caption,proto3" json:"caption,omitempty"`
	// Filename of the message (if applicable).
	Filename      string `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_whatsapp_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{28}
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Message) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Message) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Message) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// ConnectRequest is the request to connect to WhatsApp.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to connect (optional).
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{29}
}

func (x *ConnectRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// ConnectResponse contains the result of the connection attempt.
type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the connection was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// QR code data if authentication is required.
	QrCode        string `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{30}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

// DisconnectRequest is the request to disconnect from WhatsApp.
type DisconnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phone number to disconnect (optional).
	PhoneNumber   string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{31}
}

func (x *DisconnectRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// DisconnectResponse contains the result of the disconnection.
type DisconnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the disconnection was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{32}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_whatsapp_proto protoreflect.FileDescriptor

const file_proto_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x14proto/whatsapp.proto\x12\x05proto\"\x14\n" +
	"\x12HasContactsRequest\"\x91\x01\n" +
	"\x13HasContactsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fhas_contacts\x18\x03 \x01(\bR\vhasContacts\x12#\n" +
	"\rcontact_count\x18\x04 \x01(\x05R\fcontactCount\"\x18\n" +
	"\x16GetJoinedGroupsRequest\"w\n" +
	"\x17GetJoinedGroupsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x06groups\x18\x03 \x03(\v2\x10.proto.GroupInfoR\x06groups\"\xdf\x02\n" +
	"\tGroupInfo\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x1b\n" +
	"\towner_jid\x18\x02 \x01(\tR\bownerJid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12 \n" +
	"\ftopic_set_at\x18\x05 \x01(\x03R\n" +
	"topicSetAt\x12 \n" +
	"\ftopic_set_by\x18\x06 \x01(\tR\n" +
	"topicSetBy\x12*\n" +
	"\x11linked_parent_jid\x18\a \x01(\tR\x0flinkedParentJid\x12/\n" +
	"\x14is_default_sub_group\x18\b \x01(\bR\x11isDefaultSubGroup\x12\x1b\n" +
	"\tis_parent\x18\t \x01(\bR\bisParent\x12;\n" +
	"\fparticipants\x18\n" +
	" \x03(\v2\x17.proto.GroupParticipantR\fparticipants\":\n" +
	"\x13IsOnWhatsAppRequest\x12#\n" +
	"\rphone_numbers\x18\x01 \x03(\tR\fphoneNumbers\"}\n" +
	"\x14IsOnWhatsAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\aresults\x18\x03 \x03(\v2\x17.proto.OnWhatsAppResultR\aresults\"_\n" +
	"\x10OnWhatsAppResult\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03jid\x18\x02 \x01(\tR\x03jid\x12#\n" +
	"\ris_registered\x18\x03 \x01(\bR\fisRegistered\"\x0e\n" +
	"\fGetMeRequest\"U\n" +
	"\rGetMeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03jid\x18\x03 \x01(\tR\x03jid\"2\n" +
	"\x13GetGroupInfoRequest\x12\x1b\n" +
	"\tgroup_jid\x18\x01 \x01(\tR\bgroupJid\"\x9b\x01\n" +
	"\x14GetGroupInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12;\n" +
	"\fparticipants\x18\x04 \x03(\v2\x17.proto.GroupParticipantR\fparticipants\"\xed\x01\n" +
	"\x10GroupParticipant\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\x12$\n" +
	"\x0eis_super_admin\x18\x03 \x01(\bR\fisSuperAdmin\x12\x10\n" +
	"\x03lid\x18\x04 \x01(\tR\x03lid\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12.\n" +
	"\x13profile_picture_url\x18\x06 \x01(\tR\x11profilePictureUrl\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\"5\n" +
	"\x10RefreshQRRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"4\n" +
	"\x0fWALogoutRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"F\n" +
	"\x10WALogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\x13CreateStatusRequest\x12/\n" +
	"\acontent\x18\x01 \x01(\v2\x15.proto.MessageContentR\acontent\x12)\n" +
	"\x10background_color\x18\x02 \x01(\tR\x0fbackgroundColor\x12\x12\n" +
	"\x04font\x18\x03 \x01(\x05R\x04font\x12\x1f\n" +
	"\vtarget_jids\x18\x04 \x03(\tR\n" +
	"targetJids\"g\n" +
	"\x14CreateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tstatus_id\x18\x03 \x01(\tR\bstatusId\"U\n" +
	"\x12SendMessageRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x15.proto.MessageContentR\acontent\"\xb9\x02\n" +
	"\x0eMessageContent\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12+\n" +
	"\x05media\x18\x02 \x01(\v2\x13.proto.MediaContentH\x00R\x05media\x124\n" +
	"\blocation\x18\x03 \x01(\v2\x16.proto.LocationContentH\x00R\blocation\x12A\n" +
	"\rlive_location\x18\x04 \x01(\v2\x1a.proto.LiveLocationContentH\x00R\fliveLocation\x12(\n" +
	"\x04poll\x18\x05 \x01(\v2\x12.proto.PollContentH\x00R\x04poll\x121\n" +
	"\acontact\x18\x06 \x01(\v2\x15.proto.ContactContentH\x00R\acontactB\x0e\n" +
	"\fcontent_type\"y\n" +
	"\x0fLocationContent\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"\xd5\x02\n" +
	"\x13LiveLocationContent\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12,\n" +
	"\x12accuracy_in_meters\x18\x03 \x01(\rR\x10accuracyInMeters\x12 \n" +
	"\fspeed_in_mps\x18\x04 \x01(\rR\n" +
	"speedInMps\x12P\n" +
	"%degrees_clockwise_from_magnetic_north\x18\x05 \x01(\rR!degreesClockwiseFromMagneticNorth\x12\x18\n" +
	"\acaption\x18\x06 \x01(\tR\acaption\x12'\n" +
	"\x0fsequence_number\x18\a \x01(\x03R\x0esequenceNumber\x12\x1f\n" +
	"\vtime_offset\x18\b \x01(\rR\n" +
	"timeOffset\"u\n" +
	"\vPollContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x128\n" +
	"\x18selectable_options_count\x18\x03 \x01(\rR\x16selectableOptionsCount\"I\n" +
	"\x0eContactContent\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05vcard\x18\x02 \x01(\tR\x05vcard\"\xb0\x01\n" +
	"\fMediaContent\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x1a\n" +
	"\bmimetype\x18\x05 \x01(\tR\bmimetype\x12\x1b\n" +
	"\tview_once\x18\x06 \x01(\bR\bviewOnce\"w\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\">\n" +
	"\x12GetMessagesRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"A\n" +
	"\x13GetMessagesResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\"\xbe\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12\x18\n" +
	"\acaption\x18\x06 \x01(\tR\acaption\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\"3\n" +
	"\x0eConnectRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"^\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aqr_code\x18\x03 \x01(\tR\x06qrCode\"6\n" +
	"\x11DisconnectRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"H\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xba\x06\n" +
	"\x0fWhatsAppService\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse\x12D\n" +
	"\vGetMessages\x12\x19.proto.GetMessagesRequest\x1a\x1a.proto.GetMessagesResponse\x128\n" +
	"\aConnect\x12\x15.proto.ConnectRequest\x1a\x16.proto.ConnectResponse\x12A\n" +
	"\n" +
	"Disconnect\x12\x18.proto.DisconnectRequest\x1a\x19.proto.DisconnectResponse\x129\n" +
	"\x06Logout\x12\x16.proto.WALogoutRequest\x1a\x17.proto.WALogoutResponse\x12<\n" +
	"\tRefreshQR\x12\x17.proto.RefreshQRRequest\x1a\x16.proto.ConnectResponse\x12G\n" +
	"\fGetGroupInfo\x12\x1a.proto.GetGroupInfoRequest\x1a\x1b.proto.GetGroupInfoResponse\x122\n" +
	"\x05GetMe\x12\x13.proto.GetMeRequest\x1a\x14.proto.GetMeResponse\x12G\n" +
	"\fIsOnWhatsApp\x12\x1a.proto.IsOnWhatsAppRequest\x1a\x1b.proto.IsOnWhatsAppResponse\x12P\n" +
	"\x0fGetJoinedGroups\x12\x1d.proto.GetJoinedGroupsRequest\x1a\x1e.proto.GetJoinedGroupsResponse\x12G\n" +
	"\fCreateStatus\x12\x1a.proto.CreateStatusRequest\x1a\x1b.proto.CreateStatusResponse\x12D\n" +
	"\vHasContacts\x12\x19.proto.HasContactsRequest\x1a\x1a.proto.HasContactsResponseB\x18Z\x16service-platform/protob\x06proto3"

var (
	file_proto_whatsapp_proto_rawDescOnce sync.Once
	file_proto_whatsapp_proto_rawDescData []byte
)

func file_proto_whatsapp_proto_rawDescGZIP() []byte {
	file_proto_whatsapp_proto_rawDescOnce.Do(func() {
		file_proto_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whatsapp_proto_rawDesc), len(file_proto_whatsapp_proto_rawDesc)))
	})
	return file_proto_whatsapp_proto_rawDescData
}

var file_proto_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_whatsapp_proto_goTypes = []any{
	(*HasContactsRequest)(nil),      // 0: proto.HasContactsRequest
	(*HasContactsResponse)(nil),     // 1: proto.HasContactsResponse
	(*GetJoinedGroupsRequest)(nil),  // 2: proto.GetJoinedGroupsRequest
	(*GetJoinedGroupsResponse)(nil), // 3: proto.GetJoinedGroupsResponse
	(*GroupInfo)(nil),               // 4: proto.GroupInfo
	(*IsOnWhatsAppRequest)(nil),     // 5: proto.IsOnWhatsAppRequest
	(*IsOnWhatsAppResponse)(nil),    // 6: proto.IsOnWhatsAppResponse
	(*OnWhatsAppResult)(nil),        // 7: proto.OnWhatsAppResult
	(*GetMeRequest)(nil),            // 8: proto.GetMeRequest
	(*GetMeResponse)(nil),           // 9: proto.GetMeResponse
	(*GetGroupInfoRequest)(nil),     // 10: proto.GetGroupInfoRequest
	(*GetGroupInfoResponse)(nil),    // 11: proto.GetGroupInfoResponse
	(*GroupParticipant)(nil),        // 12: proto.GroupParticipant
	(*RefreshQRRequest)(nil),        // 13: proto.RefreshQRRequest
	(*WALogoutRequest)(nil),         // 14: proto.WALogoutRequest
	(*WALogoutResponse)(nil),        // 15: proto.WALogoutResponse
	(*CreateStatusRequest)(nil),     // 16: proto.CreateStatusRequest
	(*CreateStatusResponse)(nil),    // 17: proto.CreateStatusResponse
	(*SendMessageRequest)(nil),      // 18: proto.SendMessageRequest
	(*MessageContent)(nil),          // 19: proto.MessageContent
	(*LocationContent)(nil),         // 20: proto.LocationContent
	(*LiveLocationContent)(nil),     // 21: proto.LiveLocationContent
	(*PollContent)(nil),             // 22: proto.PollContent
	(*ContactContent)(nil),          // 23: proto.ContactContent
	(*MediaContent)(nil),            // 24: proto.MediaContent
	(*SendMessageResponse)(nil),     // 25: proto.SendMessageResponse
	(*GetMessagesRequest)(nil),      // 26: proto.GetMessagesRequest
	(*GetMessagesResponse)(nil),     // 27: proto.GetMessagesResponse
	(*Message)(nil),                 // 28: proto.Message
	(*ConnectRequest)(nil),          // 29: proto.ConnectRequest
	(*ConnectResponse)(nil),         // 30: proto.ConnectResponse
	(*DisconnectRequest)(nil),       // 31: proto.DisconnectRequest
	(*DisconnectResponse)(nil),      // 32: proto.DisconnectResponse
}
var file_proto_whatsapp_proto_depIdxs = []int32{
	4,  // 0: proto.GetJoinedGroupsResponse.groups:type_name -> proto.GroupInfo
	12, // 1: proto.GroupInfo.participants:type_name -> proto.GroupParticipant
	7,  // 2: proto.IsOnWhatsAppResponse.results:type_name -> proto.OnWhatsAppResult
	12, // 3: proto.GetGroupInfoResponse.participants:type_name -> proto.GroupParticipant
	19, // 4: proto.CreateStatusRequest.content:type_name -> proto.MessageContent
	19, // 5: proto.SendMessageRequest.content:type_name -> proto.MessageContent
	24, // 6: proto.MessageContent.media:type_name -> proto.MediaContent
	20, // 7: proto.MessageContent.location:type_name -> proto.LocationContent
	21, // 8: proto.MessageContent.live_location:type_name -> proto.LiveLocationContent
	22, // 9: proto.MessageContent.poll:type_name -> proto.PollContent
	23, // 10: proto.MessageContent.contact:type_name -> proto.ContactContent
	28, // 11: proto.GetMessagesResponse.messages:type_name -> proto.Message
	18, // 12: proto.WhatsAppService.SendMessage:input_type -> proto.SendMessageRequest
	26, // 13: proto.WhatsAppService.GetMessages:input_type -> proto.GetMessagesRequest
	29, // 14: proto.WhatsAppService.Connect:input_type -> proto.ConnectRequest
	31, // 15: proto.WhatsAppService.Disconnect:input_type -> proto.DisconnectRequest
	14, // 16: proto.WhatsAppService.Logout:input_type -> proto.WALogoutRequest
	13, // 17: proto.WhatsAppService.RefreshQR:input_type -> proto.RefreshQRRequest
	10, // 18: proto.WhatsAppService.GetGroupInfo:input_type -> proto.GetGroupInfoRequest
	8,  // 19: proto.WhatsAppService.GetMe:input_type -> proto.GetMeRequest
	5,  // 20: proto.WhatsAppService.IsOnWhatsApp:input_type -> proto.IsOnWhatsAppRequest
	2,  // 21: proto.WhatsAppService.GetJoinedGroups:input_type -> proto.GetJoinedGroupsRequest
	16, // 22: proto.WhatsAppService.CreateStatus:input_type -> proto.CreateStatusRequest
	0,  // 23: proto.WhatsAppService.HasContacts:input_type -> proto.HasContactsRequest
	25, // 24: proto.WhatsAppService.SendMessage:output_type -> proto.SendMessageResponse
	27, // 25: proto.WhatsAppService.GetMessages:output_type -> proto.GetMessagesResponse
	30, // 26: proto.WhatsAppService.Connect:output_type -> proto.ConnectResponse
	32, // 27: proto.WhatsAppService.Disconnect:output_type -> proto.DisconnectResponse
	15, // 28: proto.WhatsAppService.Logout:output_type -> proto.WALogoutResponse
	30, // 29: proto.WhatsAppService.RefreshQR:output_type -> proto.ConnectResponse
	11, // 30: proto.WhatsAppService.GetGroupInfo:output_type -> proto.GetGroupInfoResponse
	9,  // 31: proto.WhatsAppService.GetMe:output_type -> proto.GetMeResponse
	6,  // 32: proto.WhatsAppService.IsOnWhatsApp:output_type -> proto.IsOnWhatsAppResponse
	3,  // 33: proto.WhatsAppService.GetJoinedGroups:output_type -> proto.GetJoinedGroupsResponse
	17, // 34: proto.WhatsAppService.CreateStatus:output_type -> proto.CreateStatusResponse
	1,  // 35: proto.WhatsAppService.HasContacts:output_type -> proto.HasContactsResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_whatsapp_proto_init() }
func file_proto_whatsapp_proto_init() {
	if File_proto_whatsapp_proto != nil {
		return
	}
	file_proto_whatsapp_proto_msgTypes[19].OneofWrappers = []any{
		(*MessageContent_Text)(nil),
		(*MessageContent_Media)(nil),
		(*MessageContent_Location)(nil),
		(*MessageContent_LiveLocation)(nil),
		(*MessageContent_Poll)(nil),
		(*MessageContent_Contact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whatsapp_proto_rawDesc), len(file_proto_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_whatsapp_proto_goTypes,
		DependencyIndexes: file_proto_whatsapp_proto_depIdxs,
		MessageInfos:      file_proto_whatsapp_proto_msgTypes,
	}.Build()
	File_proto_whatsapp_proto = out.File
	file_proto_whatsapp_proto_goTypes = nil
	file_proto_whatsapp_proto_depIdxs = nil
}
