// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/whatsapp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhatsAppService_SendMessage_FullMethodName       = "/proto.WhatsAppService/SendMessage"
	WhatsAppService_GetMessages_FullMethodName       = "/proto.WhatsAppService/GetMessages"
	WhatsAppService_Connect_FullMethodName           = "/proto.WhatsAppService/Connect"
	WhatsAppService_Disconnect_FullMethodName        = "/proto.WhatsAppService/Disconnect"
	WhatsAppService_Logout_FullMethodName            = "/proto.WhatsAppService/Logout"
	WhatsAppService_IsConnected_FullMethodName       = "/proto.WhatsAppService/IsConnected"
	WhatsAppService_RefreshQR_FullMethodName         = "/proto.WhatsAppService/RefreshQR"
	WhatsAppService_GetGroupInfo_FullMethodName      = "/proto.WhatsAppService/GetGroupInfo"
	WhatsAppService_GetMe_FullMethodName             = "/proto.WhatsAppService/GetMe"
	WhatsAppService_IsOnWhatsApp_FullMethodName      = "/proto.WhatsAppService/IsOnWhatsApp"
	WhatsAppService_GetJoinedGroups_FullMethodName   = "/proto.WhatsAppService/GetJoinedGroups"
	WhatsAppService_CreateStatus_FullMethodName      = "/proto.WhatsAppService/CreateStatus"
	WhatsAppService_HasContacts_FullMethodName       = "/proto.WhatsAppService/HasContacts"
	WhatsAppService_GetProfilePicture_FullMethodName = "/proto.WhatsAppService/GetProfilePicture"
)

// WhatsAppServiceClient is the client API for WhatsAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WhatsAppService provides functionality to interact with WhatsApp via whatsmeow.
type WhatsAppServiceClient interface {
	// SendMessage sends a message to a WhatsApp user or group.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// GetMessages retrieves message history.
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// Connect establishes a connection to WhatsApp.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Disconnect closes the connection to WhatsApp.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Logout logs out the current session.
	Logout(ctx context.Context, in *WALogoutRequest, opts ...grpc.CallOption) (*WALogoutResponse, error)
	// IsConnected checks if the WhatsApp client is currently connected.
	IsConnected(ctx context.Context, in *IsConnectedRequest, opts ...grpc.CallOption) (*IsConnectedResponse, error)
	// RefreshQR forces a new QR code generation for login.
	RefreshQR(ctx context.Context, in *RefreshQRRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// GetGroupInfo retrieves information about a specific group.
	GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error)
	// GetMe retrieves information about the current user.
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	// IsOnWhatsApp checks if phone numbers are registered on WhatsApp.
	IsOnWhatsApp(ctx context.Context, in *IsOnWhatsAppRequest, opts ...grpc.CallOption) (*IsOnWhatsAppResponse, error)
	// GetJoinedGroups retrieves a list of groups the user has joined.
	GetJoinedGroups(ctx context.Context, in *GetJoinedGroupsRequest, opts ...grpc.CallOption) (*GetJoinedGroupsResponse, error)
	// CreateStatus posts a status update (story).
	CreateStatus(ctx context.Context, in *CreateStatusRequest, opts ...grpc.CallOption) (*CreateStatusResponse, error)
	// HasContacts checks if the user has any contacts.
	HasContacts(ctx context.Context, in *HasContactsRequest, opts ...grpc.CallOption) (*HasContactsResponse, error)
	// GetProfilePicture retrieves a user's profile picture.
	GetProfilePicture(ctx context.Context, in *GetProfilePictureRequest, opts ...grpc.CallOption) (*GetProfilePictureResponse, error)
}

type whatsAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhatsAppServiceClient(cc grpc.ClientConnInterface) WhatsAppServiceClient {
	return &whatsAppServiceClient{cc}
}

func (c *whatsAppServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) Logout(ctx context.Context, in *WALogoutRequest, opts ...grpc.CallOption) (*WALogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WALogoutResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) IsConnected(ctx context.Context, in *IsConnectedRequest, opts ...grpc.CallOption) (*IsConnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsConnectedResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_IsConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) RefreshQR(ctx context.Context, in *RefreshQRRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_RefreshQR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) IsOnWhatsApp(ctx context.Context, in *IsOnWhatsAppRequest, opts ...grpc.CallOption) (*IsOnWhatsAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsOnWhatsAppResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_IsOnWhatsApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) GetJoinedGroups(ctx context.Context, in *GetJoinedGroupsRequest, opts ...grpc.CallOption) (*GetJoinedGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJoinedGroupsResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_GetJoinedGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) CreateStatus(ctx context.Context, in *CreateStatusRequest, opts ...grpc.CallOption) (*CreateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_CreateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) HasContacts(ctx context.Context, in *HasContactsRequest, opts ...grpc.CallOption) (*HasContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasContactsResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_HasContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppServiceClient) GetProfilePicture(ctx context.Context, in *GetProfilePictureRequest, opts ...grpc.CallOption) (*GetProfilePictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfilePictureResponse)
	err := c.cc.Invoke(ctx, WhatsAppService_GetProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhatsAppServiceServer is the server API for WhatsAppService service.
// All implementations must embed UnimplementedWhatsAppServiceServer
// for forward compatibility.
//
// WhatsAppService provides functionality to interact with WhatsApp via whatsmeow.
type WhatsAppServiceServer interface {
	// SendMessage sends a message to a WhatsApp user or group.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// GetMessages retrieves message history.
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// Connect establishes a connection to WhatsApp.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Disconnect closes the connection to WhatsApp.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Logout logs out the current session.
	Logout(context.Context, *WALogoutRequest) (*WALogoutResponse, error)
	// IsConnected checks if the WhatsApp client is currently connected.
	IsConnected(context.Context, *IsConnectedRequest) (*IsConnectedResponse, error)
	// RefreshQR forces a new QR code generation for login.
	RefreshQR(context.Context, *RefreshQRRequest) (*ConnectResponse, error)
	// GetGroupInfo retrieves information about a specific group.
	GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GetGroupInfoResponse, error)
	// GetMe retrieves information about the current user.
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	// IsOnWhatsApp checks if phone numbers are registered on WhatsApp.
	IsOnWhatsApp(context.Context, *IsOnWhatsAppRequest) (*IsOnWhatsAppResponse, error)
	// GetJoinedGroups retrieves a list of groups the user has joined.
	GetJoinedGroups(context.Context, *GetJoinedGroupsRequest) (*GetJoinedGroupsResponse, error)
	// CreateStatus posts a status update (story).
	CreateStatus(context.Context, *CreateStatusRequest) (*CreateStatusResponse, error)
	// HasContacts checks if the user has any contacts.
	HasContacts(context.Context, *HasContactsRequest) (*HasContactsResponse, error)
	// GetProfilePicture retrieves a user's profile picture.
	GetProfilePicture(context.Context, *GetProfilePictureRequest) (*GetProfilePictureResponse, error)
	mustEmbedUnimplementedWhatsAppServiceServer()
}

// UnimplementedWhatsAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhatsAppServiceServer struct{}

func (UnimplementedWhatsAppServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedWhatsAppServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedWhatsAppServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWhatsAppServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedWhatsAppServiceServer) Logout(context.Context, *WALogoutRequest) (*WALogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedWhatsAppServiceServer) IsConnected(context.Context, *IsConnectedRequest) (*IsConnectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsConnected not implemented")
}
func (UnimplementedWhatsAppServiceServer) RefreshQR(context.Context, *RefreshQRRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshQR not implemented")
}
func (UnimplementedWhatsAppServiceServer) GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GetGroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedWhatsAppServiceServer) GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedWhatsAppServiceServer) IsOnWhatsApp(context.Context, *IsOnWhatsAppRequest) (*IsOnWhatsAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsOnWhatsApp not implemented")
}
func (UnimplementedWhatsAppServiceServer) GetJoinedGroups(context.Context, *GetJoinedGroupsRequest) (*GetJoinedGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJoinedGroups not implemented")
}
func (UnimplementedWhatsAppServiceServer) CreateStatus(context.Context, *CreateStatusRequest) (*CreateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStatus not implemented")
}
func (UnimplementedWhatsAppServiceServer) HasContacts(context.Context, *HasContactsRequest) (*HasContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasContacts not implemented")
}
func (UnimplementedWhatsAppServiceServer) GetProfilePicture(context.Context, *GetProfilePictureRequest) (*GetProfilePictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfilePicture not implemented")
}
func (UnimplementedWhatsAppServiceServer) mustEmbedUnimplementedWhatsAppServiceServer() {}
func (UnimplementedWhatsAppServiceServer) testEmbeddedByValue()                         {}

// UnsafeWhatsAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhatsAppServiceServer will
// result in compilation errors.
type UnsafeWhatsAppServiceServer interface {
	mustEmbedUnimplementedWhatsAppServiceServer()
}

func RegisterWhatsAppServiceServer(s grpc.ServiceRegistrar, srv WhatsAppServiceServer) {
	// If the following call panics, it indicates UnimplementedWhatsAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhatsAppService_ServiceDesc, srv)
}

func _WhatsAppService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WALogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).Logout(ctx, req.(*WALogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_IsConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).IsConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_IsConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).IsConnected(ctx, req.(*IsConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_RefreshQR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).RefreshQR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_RefreshQR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).RefreshQR(ctx, req.(*RefreshQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).GetGroupInfo(ctx, req.(*GetGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_IsOnWhatsApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnWhatsAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).IsOnWhatsApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_IsOnWhatsApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).IsOnWhatsApp(ctx, req.(*IsOnWhatsAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_GetJoinedGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJoinedGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).GetJoinedGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_GetJoinedGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).GetJoinedGroups(ctx, req.(*GetJoinedGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_CreateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).CreateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_CreateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).CreateStatus(ctx, req.(*CreateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_HasContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).HasContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_HasContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).HasContacts(ctx, req.(*HasContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppService_GetProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppServiceServer).GetProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppService_GetProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppServiceServer).GetProfilePicture(ctx, req.(*GetProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhatsAppService_ServiceDesc is the grpc.ServiceDesc for WhatsAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhatsAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WhatsAppService",
	HandlerType: (*WhatsAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _WhatsAppService_SendMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _WhatsAppService_GetMessages_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _WhatsAppService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _WhatsAppService_Disconnect_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _WhatsAppService_Logout_Handler,
		},
		{
			MethodName: "IsConnected",
			Handler:    _WhatsAppService_IsConnected_Handler,
		},
		{
			MethodName: "RefreshQR",
			Handler:    _WhatsAppService_RefreshQR_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _WhatsAppService_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _WhatsAppService_GetMe_Handler,
		},
		{
			MethodName: "IsOnWhatsApp",
			Handler:    _WhatsAppService_IsOnWhatsApp_Handler,
		},
		{
			MethodName: "GetJoinedGroups",
			Handler:    _WhatsAppService_GetJoinedGroups_Handler,
		},
		{
			MethodName: "CreateStatus",
			Handler:    _WhatsAppService_CreateStatus_Handler,
		},
		{
			MethodName: "HasContacts",
			Handler:    _WhatsAppService_HasContacts_Handler,
		},
		{
			MethodName: "GetProfilePicture",
			Handler:    _WhatsAppService_GetProfilePicture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/whatsapp.proto",
}
