EMAIL:
  HOST: "smtp.gmail.com"
  PORT: 587
  USERNAME: "service4@csna4u.com"
  # PASSWORD: "service.12345"
  PASSWORD: "ejdw ezvf hemy rwhj"
  MAX_RETRY: 60
  RETRY_DELAY: 30

DEFAULT:
  # TA_FEEDBACK_URL: "http://127.0.0.1:41492/feedback_ta" # Old => hit the odoo_wa.service
  TA_FEEDBACK_URL: "http://127.0.0.1:2221/ta/feedback_by_ta" # New => hit the API of WebPanel.service

ODOO:
  JSONRPC: "2.0"
  # Manage Service #####################################################################
  LOGIN: desta@smartwebindonesia.com
  PASSWORD: Makan198
  DB: gsa_db
  # URL_SESSION: https://192.101.1.66:8069/web/session/authenticate # Development 20080
  # URL_GETDATA: https://192.101.1.66:8069/api/getdata
  URL_SESSION: https://www.gsa4u.net:13070/web/session/authenticate
  URL_GETDATA: https://www.gsa4u.net:13070/api/getdata
  # ATM ################################################################################
  LOGIN_ATM: made@smartwebindonesia.com
  PASSWORD_ATM: 12345678
  DB_ATM: field_service_db
  URL_SESSION_ATM: https://atmms.csna4u.com:8087/web/session/authenticate
  URL_GETDATA_ATM: https://atmms.csna4u.com:8087/api/getdata
  MAX_RETRY: 10
  RETRY_DELAY: 5
  SESSION_TIMEOUT: "300s"
  GETDATA_TIMEOUT: "1000m"
  COMPANY_ALLOWED: [13, 21, 19, 20, 15, 12, 3, 26] # ARTAJASA,DANA,DKI,MANDIRI,MTI,NDP,OVO,SINARMAS
  
REPORT:
  TO:
    # - "wegirandol@smartwebindonesia.com"
    # - "fauziab@csna4u.com"
    # - "tetty_m@csna4u.com"
    # - "denifajarpratama@csna4u.com"
    # - "arippradana@csna4u.com"
    # - "noviamalia.anggraini@csna4u.com"
    # - "tia_s@smartwebindonesia.com"
    # - "vera_p@smartwebindonesia.com"
    # - "heriandi@csna4u.com"
    # - "budi.sumantri@csna4u.com"
    # - "septianrizki@csna4u.com"    
    # - "rafy_m@csna4u.com"    
    # - "abdunopriyarasyiddinn@csna4u.com"
  CC:
    # - "oliver@csna4u.com"
    # - "cindychang@cybersoft.com.tw"
    # - "nadia.kristina@csna4u.com"
    # - "nickenb@csna4u.com"
    # - "made@smartwebindonesia.com"
    # - "lilimarlina@smartwebindonesia.com"
    # - "tetty_m@csna4u.com"
    # - "tetty.sintauli@smartwebindonesia.com"
  BCC:

GIN_MODE: "release"
REDIS_HOST: "127.0.0.1"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""
REDIS_DB: "3"
WHATSAPP_REDIS_DB: "6"

# MYSQL_HOST_DB: "192.168.20.38"
# MYSQL_PORT_DB: "6033"
# MYSQL_USER_DB: "cideng_db"
# MYSQL_PASS_DB: "Takasitau"
# MYSQL_NAME_DB: "web_ta_csna"
MYSQL_HOST_DB: "127.0.0.1"
MYSQL_PORT_DB: "3306"
MYSQL_USER_DB: "swi"
MYSQL_PASS_DB: "Takasitau"
MYSQL_NAME_DB: "web_technical_assistance"
MYSQL_NAME_CALL_CENTER_DB: "call_center_new_db # Not use"

# PROD
# MYSQL_HOST_DB_KONFIRMASI_PENGERJAAN: "127.0.0.1"
# MYSQL_PORT_DB_KONFIRMASI_PENGERJAAN: "3306"
MYSQL_HOST_DB_KONFIRMASI_PENGERJAAN: "192.153.5.7"
MYSQL_PORT_DB_KONFIRMASI_PENGERJAAN: "3310"
MYSQL_USER_DB_KONFIRMASI_PENGERJAAN: "swi"
MYSQL_PASS_DB_KONFIRMASI_PENGERJAAN: "Takasitau"
MYSQL_NAME_DB_KONFIRMASI_PENGERJAAN: "odoo_pending"
APP_LISTEN: ":31425"
WEB_PUBLIC_URL: "https://paxstorenewdownload.csna4u.com:3420"
FILESTORE_URL: "http://146.196.106.203:65029"
# FILESTORE_URL: "http://127.0.0.1:22441"
# WO_DETAIL_URL: "http://smartwebindonesia.com:3405"
WO_DETAIL_URL: "https://paxstorenewdownload.csna4u.com:3420"
WHATSAPP_CIDENG_SERVER: "192.168.2.242"
ENDPOINT_KUKUH_GET_DATA: "http://192.101.1.149:31425/here/getData"
APP_NAME: "TA CSNA"
APP_LOGO: "/assets/self/img/csna.jpeg"
APP_VERSION_NO: "4"
APP_VERSION_CODE: "2.0.0.2025.10.14"
APP_VERSION_NAME: "technical_assistance_csna"
APP_STATIC_DIR: "./web"
APP_PUBLISHED_DIR: "assets|page|log"  #|dist|fonts|js|libs|scss|tasks|uploads #|page|log
APP_LOG_DIR: "./log"
APP_UPLOAD_DIR: "./uploads"
CONFIG_SMTP_HOST: "smtp.gmail.com"
CONFIG_SMTP_PORT: "587"
CONFIG_AUTH_EMAIL: "service4@csna4u.com"
CONFIG_AUTH_PASSWORD: "service.12345"
CONFIG_SMTP_SENDER: "smartwebindonesia@csna.com"
LOGIN_TIME_M: "900"
COOKIE_LOGIN_DOMAIN: ""
COOKIE_LOGIN_SECURE: "false"
MAX_DISCONECTION_TIME_S: "12"
AES_KEY: "w4GwYyADnBa91vph1vCLRghvfkTmaWRF"
AES_KEY_IV: "xu1HErEpSpaf87D7"

